# Generates frontend/src/generated/contracts.ts from contracts/schemas JSON Schema files.
# Hand-rolled property/required extractor (no JSON Schema codegen dependency).
# Usage: powershell -File scripts/generate-contract-types.ps1

$ErrorActionPreference = 'Stop'

$Root = Resolve-Path (Join-Path $PSScriptRoot '..')
$Schemas = Join-Path $Root 'contracts/schemas'
$OutDir = Join-Path $Root 'frontend/src/generated'
$OutFile = Join-Path $OutDir 'contracts.ts'

function Get-SchemaShape {
    param(
        [Parameter(Mandatory = $true)][string]$RelativePath,
        [Parameter(Mandatory = $true)][string]$ExportPrefix
    )
    $path = Join-Path $Schemas $RelativePath
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Schema not found: $path"
    }
    $schema = Get-Content -LiteralPath $path -Raw -Encoding UTF8 | ConvertFrom-Json
    $required = @()
    if ($null -ne $schema.required) {
        foreach ($item in @($schema.required)) {
            $required += [string]$item
        }
    }
    $properties = @()
    if ($null -ne $schema.properties) {
        foreach ($prop in $schema.properties.PSObject.Properties) {
            $properties += [string]$prop.Name
        }
    }
    $optional = @($properties | Where-Object { $_ -notin $required })
    [pscustomobject]@{
        RelativePath = $RelativePath
        ExportPrefix = $ExportPrefix
        Required     = $required
        Properties   = $properties
        Optional     = $optional
    }
}

function Format-TsStringArray {
    param([string[]]$Items)
    if ($null -eq $Items -or $Items.Count -eq 0) {
        return '[] as const'
    }
    $quoted = $Items | ForEach-Object { "  '$($_.Replace("'", "\'"))'" }
    # Emit a real readonly tuple; parentheses would create a comma expression.
    return "[`n$($quoted -join ",`n")`n] as const"
}

function Format-TsStubType {
    param(
        [string]$Name,
        [string[]]$Required,
        [string[]]$Optional
    )
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("/** Generated field stub from JSON Schema (not a full wire parser). */")
    $lines.Add("export type ${Name}GeneratedStub = {")
    foreach ($field in $Required) {
        $lines.Add("  $field`: unknown")
    }
    foreach ($field in $Optional) {
        $lines.Add("  $field`?: unknown")
    }
    $lines.Add('}')
    return ($lines -join "`n")
}

$shapes = @(
    (Get-SchemaShape -RelativePath 'api/finding.v1.json' -ExportPrefix 'Finding'),
    (Get-SchemaShape -RelativePath 'domain/security-hypothesis.v1.json' -ExportPrefix 'SecurityHypothesis'),
    (Get-SchemaShape -RelativePath 'domain/coverage-matrix.v1.json' -ExportPrefix 'CoverageMatrix')
)

$generatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/* eslint-disable */')
[void]$sb.AppendLine('/**')
[void]$sb.AppendLine(' * GENERATED FILE - do not edit by hand.')
[void]$sb.AppendLine(' * Source: contracts/schemas (JSON Schema required/properties).')
[void]$sb.AppendLine(" * Regenerated by: scripts/generate-contract-types.ps1 ($generatedAt)")
[void]$sb.AppendLine(' */')
[void]$sb.AppendLine('')

foreach ($shape in $shapes) {
    $reqConst = "$($shape.ExportPrefix)RequiredFields"
    $optConst = "$($shape.ExportPrefix)OptionalFields"
    $allConst = "$($shape.ExportPrefix)PropertyFields"
    [void]$sb.AppendLine("/** Schema: $($shape.RelativePath) - required */")
    [void]$sb.AppendLine("export const $reqConst = $(Format-TsStringArray $shape.Required)")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("/** Schema: $($shape.RelativePath) - optional properties */")
    [void]$sb.AppendLine("export const $optConst = $(Format-TsStringArray $shape.Optional)")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("/** Schema: $($shape.RelativePath) - all properties */")
    [void]$sb.AppendLine("export const $allConst = $(Format-TsStringArray $shape.Properties)")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine((Format-TsStubType -Name $shape.ExportPrefix -Required $shape.Required -Optional $shape.Optional))
    [void]$sb.AppendLine('')
}

[void]$sb.AppendLine('export const GENERATED_CONTRACT_SCHEMAS = [')
foreach ($shape in $shapes) {
    [void]$sb.AppendLine("  '$($shape.RelativePath)',")
}
[void]$sb.AppendLine('] as const')
[void]$sb.AppendLine('')

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutFile, $sb.ToString(), $utf8NoBom)
Write-Host "Wrote $OutFile"
foreach ($shape in $shapes) {
    Write-Host ("  {0}: required={1} optional={2}" -f $shape.ExportPrefix, $shape.Required.Count, $shape.Optional.Count)
}
