#!/usr/bin/env python3
"""Phase 2: domain package comment translations."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

REPLACEMENTS = [
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerCapability.java",
     "* Negotiated Analyzer capabilities. Unknown values are rejected during negotiation",
     "* 协商后的 Analyzer capability。未知值在协商时被拒绝"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerEvidenceStore.java",
     "* Port for atomic publish of validated Analyzer evidence.",
     "* 已校验 Analyzer evidence 原子发布的 port。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerEvidenceStore.java",
     "* Implementations must not grant Analyzer DB/model/authorization/Worker rights.",
     "* 实现不得授予 Analyzer DB/model/authorization/Worker 权限。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerIngress.java",
     "* Control-plane Analyzer ingress: bounded staging → full validation → atomic evidence publish.",
     "* Control Plane Analyzer ingress：有界 staging → 完整校验 → 原子 evidence 发布。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerIngress.java",
     "* Partial / rejected submissions never enter the authoritative evidence store.",
     "* 部分/被拒绝的 submission 永不进入权威 evidence store。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerIngress.java",
     "        // Scope/deadline authorization must precede idempotency replay. A submission id",
     "        // scope/deadline 授权必须先于 idempotency replay。submission id"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerIngress.java",
     "        // is globally indexed, so a valid session from another scan must not receive it.",
     "        // 全局索引，故另一 scan 的有效 session 不得接收它。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerIngress.java",
     "        // Explicit missing-chunk probe: gaps in staged sequences already prevented at stage time;",
     "        // 显式 missing-chunk probe：staged sequence 的 gap 已在 stage 时阻止；"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerIngress.java",
     "        // commit with fewer manifest entries than required contiguous 0..n-1 is MISSING_CHUNK.",
     "        // manifest entry 少于所需连续 0..n-1 的 commit 为 MISSING_CHUNK。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerIngress.java",
     "                    // Gaps are published from submission.coverageGaps, not as IR nodes.",
     "                    // Gap 从 submission.coverageGaps 发布，而非 IR node。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/AnalyzerIngress.java",
     "                    // Unknown kinds are retained only as diagnostics via payload; never elevate status.",
     "                    // 未知 kind 仅经 payload 保留为 diagnostic；永不提升 status。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/CapabilityNegotiation.java",
     "* Analyzer offers capabilities; Control Plane accepts a subset.",
     "* Analyzer 提供 capability；Control Plane 接受子集。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/CapabilityNegotiation.java",
     "* Unknown capabilities fail closed — they are never silently ignored.",
     "* 未知 capability fail-closed — 永不静默忽略。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/CapabilityNegotiation.java",
     "     * Accept only known capabilities that the offer includes and the server allows.",
     "     * 仅接受 offer 包含且服务端允许的已知 capability。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/InMemoryAnalyzerEvidenceStore.java",
     "* Process-local Fake evidence store for Test Analyzer / contract proofs.",
     "* 进程内 Fake evidence store，用于 Test Analyzer / contract 证明。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/InMemoryAnalyzerEvidenceStore.java",
     "* Not a Control Plane SQLite adapter — Analyzers must never receive DB handles.",
     "* 非 Control Plane SQLite adapter — Analyzer 永不得接收 DB handle。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/IrChunk.java",
     "* One IR/trace fragment staged before atomic publish.",
     "* 原子发布前 staged 的单条 IR/trace 片段。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/IrChunk.java",
     "* Payload digest covers canonical UTF-8 of sorted key=value lines for determinism.",
     "* Payload digest 覆盖排序 key=value 行的 canonical UTF-8 以保证确定性。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/TestAnalyzerProcessMain.java",
     "* Independent-process Test Analyzer entrypoint (P1-07).",
     "* 独立进程 Test Analyzer 入口（P1-07）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/TestAnalyzerProcessMain.java",
     "* versioned IR chunks for the parent to feed through {@link AnalyzerIngress}.",
     "* 版本化 IR chunk，供父进程经 {@link AnalyzerIngress} 摄入。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/TestJsLanguageAnalyzer.java",
     "* Second-language static LanguageAnalyzer stub (JavaScript / ECMAScript).",
     "* 第二语言静态 LanguageAnalyzer stub（JavaScript / ECMAScript）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/TestJsLanguageAnalyzer.java",
     "* fragments. Does not embed a JS parser in the Control Plane and grants no RuntimeAdapter",
     "* 片段。不在 Control Plane 嵌入 JS parser，也不授予 RuntimeAdapter"),
    ("src/main/java/com/aq/jvmsentinel/domain/analyzer/TestJsLanguageAnalyzer.java",
     "* or dynamic-execution rights (ADR-0001).",
     "* 或 dynamic-execution 权限（ADR-0001）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/coverage/CoverageMatrix.java",
     "* Read-only coverage matrix for a scan (P0-13). Aggregates known gaps; never invents coverage.",
     "* scan 的只读 coverage matrix（P0-13）。聚合已知 gap；永不发明 coverage。"),
    ("src/main/java/com/aq/jvmsentinel/domain/coverage/CoverageMatrix.java",
     "* SUCCESS / COMPLETED must never be interpreted as safe or secure.",
     "* SUCCESS / COMPLETED 永不得解读为 safe 或 secure。"),
    ("src/main/java/com/aq/jvmsentinel/domain/coverage/CoverageMatrix.java",
     "            // UNRESOLVED is a gap count, never covered.",
     "            // UNRESOLVED 为 gap 计数，永非 covered。"),
    ("src/main/java/com/aq/jvmsentinel/domain/coverage/CoverageMatrix.java",
     "            // Explicit: SUCCESS/COMPLETED ≠ safe/secure.",
     "            // 显式：SUCCESS/COMPLETED ≠ safe/secure。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/ExperimentPlanKind.java",
     "* Experiment plan kinds from PATH_EXPERIMENT_MODEL §6.2 (P1-06).",
     "* 来自 PATH_EXPERIMENT_MODEL §6.2 的 experiment plan kind（P1-06）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/ExperimentPlanKind.java",
     "* Unknown wire values stay empty — never invent a kind that elevates verification.",
     "* 未知 wire 值保持空 — 永不发明会提升 verification 的 kind。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/ExperimentSignal.java",
     "* Expected or counter signal declared on a hypothesis-bound experiment plan.",
     "* hypothesis-bound experiment plan 上声明的 expected 或 counter signal。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/HypothesisExperimentGate.java",
     "* Strict server-side lifecycle gate for hypothesis experiments (P1-06).",
     "* hypothesis experiment 的严格服务端 lifecycle gate（P1-06）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/HypothesisExperimentPlan.java",
     "* Server-owned experiment plan bound to a SecurityHypothesis (P1-06).",
     "* 绑定 SecurityHypothesis 的服务端 owned experiment plan（P1-06）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/HypothesisExperimentPlan.java",
     "* AI may propose fields; only the server compiles and gates lifecycle transitions.",
     "* AI 可提议 field；仅服务端编译并 gate lifecycle 转换。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/ObservationKind.java",
     "* Unified RuntimeObservation subject kinds (P1-06).",
     "* 统一的 RuntimeObservation subject kind（P1-06）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/RuntimeObservation.java",
     "* Unified runtime observation for Entry/Guard/Effect/State/Dependency/Exception (P1-06).",
     "* Entry/Guard/Effect/State/Dependency/Exception 的统一 runtime observation（P1-06）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/RuntimeObservation.java",
     "* Provenance stays RUNTIME_OBSERVED; never elevates verification status by itself.",
     "* Provenance 保持 RUNTIME_OBSERVED；自身永不提升 verification status。"),
    ("src/main/java/com/aq/jvmsentinel/domain/experiment/RuntimeObservation.java",
     "            // Empty / failed projections keep identity but must not look like hits.",
     "            // 空/失败 projection 保留 identity 但不得看起来像 hit。"),
    ("src/main/java/com/aq/jvmsentinel/domain/hypothesis/HypothesisFamily.java",
     "* SecurityHypothesis family taxonomy (ADR-0001 neutral contract).",
     "* SecurityHypothesis family 分类（ADR-0001 中立 contract）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/hypothesis/HypothesisFamily.java",
     "* Unknown wire values map to {@link #UNKNOWN} without elevating verification status.",
     "* 未知 wire 值映射为 {@link #UNKNOWN}，不提升 verification status。"),
    ("src/main/java/com/aq/jvmsentinel/domain/hypothesis/HypothesisLifecycle.java",
     "* Hypothesis lifecycle for the P0-12 vertical slice.",
     "* P0-12 垂直切片的 hypothesis lifecycle。"),
    ("src/main/java/com/aq/jvmsentinel/domain/hypothesis/HypothesisLifecycle.java",
     "* Static sink / AUTH_GAP projections start as {@link #CANDIDATE}.",
     "* 静态 sink / AUTH_GAP 投影起始于 {@link #CANDIDATE}。"),
    ("src/main/java/com/aq/jvmsentinel/domain/hypothesis/SecurityHypothesis.java",
     "* First-class security hypothesis (P0-12). Source/effect are required for DATAFLOW only.",
     "* 一等 security hypothesis（P0-12）。source/effect 仅 DATAFLOW 必填。"),
    ("src/main/java/com/aq/jvmsentinel/domain/hypothesis/SecurityHypothesis.java",
     "        // Unknown family: keep payload readable but never invent DATAFLOW source/effect requirements.",
     "        // 未知 family：保持 payload 可读，但永不发明 DATAFLOW source/effect 要求。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EdgeKind.java",
     "* Evidence Graph edge kinds (P1-02). Language-neutral; JVM call descriptors stay in extensions.",
     "* Evidence Graph edge kind（P1-02）。语言中立；JVM call descriptor 留在 extension。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EffectNode.java",
     "* Sensitive effect / sink-like capability. Not limited to fixed API signatures.",
     "* 敏感 effect / sink-like capability。不限于固定 API signature。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EntryNode.java",
     "* Entry surface (HTTP, RPC, message, task, …). AUTH-only filter rows are not EntryNodes;",
     "* Entry 面（HTTP、RPC、message、task、…）。仅 AUTH 的 filter 行不是 EntryNode；"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EntryNode.java",
     "* they project as {@link GuardNode} and are recorded as a compatibility gap.",
     "* 它们投影为 {@link GuardNode} 并记为 compatibility gap。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EvidenceGraph.java",
     "* Bounded Security IR / Evidence Graph container (P1-02).",
     "* 有界 Security IR / Evidence Graph 容器（P1-02）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EvidenceGraph.java",
     "* verification status or invents FACT provenance.",
     "* verification status 或发明 FACT provenance。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EvidenceGraph.java",
     "     * Findings whose evidenceRefs intersect this node's refs (node → finding reverse join).",
     "     * evidenceRefs 与本 node ref 相交的 finding（node → finding 反向 join）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EvidenceGraph.java",
     "     * Legacy EntryDto vs EntryNode count gap (AUTH filter rows, budget truncation, …).",
     "     * Legacy EntryDto 与 EntryNode 计数 gap（AUTH filter 行、budget 截断、…）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EvidenceGraph.java",
     "     * Restore an authoritative graph from {@link #toMap()} wire form (StaticFactSnapshot persistence).",
     "     * 从 {@link #toMap()} wire 形式恢复权威 graph（StaticFactSnapshot persistence）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EvidenceGraph.java",
     "     * Unknown node kinds are skipped fail-closed (not invented as FACT).",
     "     * 未知 node kind fail-closed 跳过（不发明为 FACT）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/EvidenceGraphMerge.java",
     "* Merges supplemental IR nodes into an existing Evidence Graph without elevating status.",
     "* 将补充 IR node 合并进现有 Evidence Graph，不提升 status。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/GuardNode.java",
     "* Auth / ownership / tenant / approval guard. AUTH EntryDto rows and AUTH_GAP signals",
     "* Auth / ownership / tenant / approval guard。AUTH EntryDto 行与 AUTH_GAP signal"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/GuardNode.java",
     "* project here rather than as {@link EntryNode}/{@link EffectNode} when appropriate.",
     "* 在适当时投影于此，而非 {@link EntryNode}/{@link EffectNode}。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/IrNode.java",
     "* Sealed Security IR node hierarchy for the Evidence Graph (P1-02).",
     "* Evidence Graph 的 sealed Security IR node 层次（P1-02）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/IrNode.java",
     "* but never elevate verification status.",
     "* 但永不提升 verification status。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/ProgramNode.java",
     "* Program element: class, method, field, instruction, config, or resource symbol.",
     "* 程序元素：class、method、field、instruction、config 或 resource symbol。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/ResourceNode.java",
     "* External resource / dependency lifecycle subject (DB, HTTP client, file, …).",
     "* 外部 resource / dependency lifecycle 主体（DB、HTTP client、file、…）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/RuntimeObservationNode.java",
     "* Runtime observation projected from PathRun / worker events.",
     "* 从 PathRun / worker event 投影的 runtime observation。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/SanitizerNode.java",
     "* Encoding / parameterization / whitelist / reject-branch sanitizer or validator.",
     "* Encoding / parameterization / whitelist / reject-branch sanitizer 或 validator。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/StableNodeIds.java",
     "* Stable Evidence Graph node ID strategy (P1-02).",
     "* 稳定 Evidence Graph node ID 策略（P1-02）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/StableNodeIds.java",
     "* They intentionally omit project/scan prefixes — those live on {@link EvidenceGraph}.",
     "* 刻意省略 project/scan 前缀 — 那些位于 {@link EvidenceGraph}。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/StableNodeIds.java",
     "* Keys reuse legacy DTO identities when present so findings can resolve",
     "* Key 在存在时复用 legacy DTO identity，以便 finding 可解析"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/StableNodeIds.java",
     "* node {@code extensions}, never into the ID namespace.",
     "* node {@code extensions}，永不进入 ID namespace。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/StateNode.java",
     "* Business / security state precondition or transition subject.",
     "* 业务/安全 state 前置条件或 transition 主体。"),
    ("src/main/java/com/aq/jvmsentinel/domain/ir/TrustBoundaryNode.java",
     "* Trust boundary / untrusted origin (parameter, header, cookie, message, file, …).",
     "* Trust boundary / 不可信 origin（parameter、header、cookie、message、file、…）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/ForcedGuardKind.java",
     "* Guard kinds eligible for FORCED_REACHABILITY. Sanitizer / SQL parameterization /",
     "* 符合 FORCED_REACHABILITY 的 guard kind。Sanitizer / SQL parameterization /"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/ForcedGuardKind.java",
     "* file-type / business state-machine invariants are never forceable.",
     "* file-type / business state-machine invariant 永不可 force。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/GuardSurface.java",
     "* Static catalog entry for a FORCED_REACHABILITY-eligible guard surface.",
     "* FORCED_REACHABILITY 合格 guard surface 的静态 catalog entry。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/GuardSurface.java",
     "* Refs are server-owned ({@code GUARD:AUTH:<simpleName>}); AI/frontend cannot supply them.",
     "* Ref 为服务端 owned（{@code GUARD:AUTH:<simpleName>}）；AI/frontend 不能提供。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/PathRunPathDebugView.java",
     "* Optional PathRun extension fields for path-debug contracts.",
     "* path-debug contract 的可选 PathRun extension field。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/PathRunPathDebugView.java",
     "* Missing fields on old PathRuns are marked LEGACY_DYNAMIC_INCOMPLETE — never backfilled.",
     "* 旧 PathRun 缺失 field 标记 LEGACY_DYNAMIC_INCOMPLETE — 永不 backfill。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/PathRunPathDebugView.java",
     "     * Compatible read of a PathRun wire map. Missing posture/trace/world fields → legacy incomplete.",
     "     * PathRun wire map 的兼容读取。缺失 posture/trace/world field → legacy incomplete。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/PathRunPathDebugView.java",
     "     * Never invents FORCED_REACHABILITY or fake PathTrace events.",
     "     * 永不发明 FORCED_REACHABILITY 或 fake PathTrace event。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/PathRunPathDebugView.java",
     "        // Always emit so GUI wire parsers see a stable array shape.",
     "        // 始终 emit，使 GUI wire parser 看到稳定 array shape。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/PathTrace.java",
     "* Ordered dynamic path for one PathRun attempt (P0-21).",
     "* 单次 PathRun attempt 的有序 dynamic path（P0-21）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/PathTrace.java",
     "* Preserves pre-failure hops/effects even when the request exits on dependency failure.",
     "* 即使 request 因 dependency failure 退出，仍保留 failure 前 hop/effect。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/RuntimePosture.java",
     "* Server-owned runtime posture for one experiment (P0-21).",
     "* 单次 experiment 的服务端 owned runtime posture（P0-21）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/RuntimePosture.java",
     "* AI/frontend cannot supply forcedGuardRefs or enable FORCED_REACHABILITY.",
     "* AI/frontend 不能提供 forcedGuardRefs 或启用 FORCED_REACHABILITY。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/RuntimePosture.java",
     "            // Never invent forced posture from incomplete legacy payloads.",
     "            // 永不从不完整 legacy payload 发明 forced posture。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/RuntimePostureKind.java",
     "* P0-21 runtime posture kinds. Wire IdentityTrack remains UNAUTH/USER/ADMIN/BYPASS_CANDIDATE;",
     "* P0-21 runtime posture kind。Wire IdentityTrack 仍为 UNAUTH/USER/ADMIN/BYPASS_CANDIDATE；"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/RuntimePostureKind.java",
     "* postureKind is the product-purpose dimension.",
     "* postureKind 为产品用途维度。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/TracePlan.java",
     "* Static bridge from Entry/Guard/Effect facts to dynamic observation targets (P0-21).",
     "* Entry/Guard/Effect fact 到 dynamic observation target 的静态桥（P0-21）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/WorldPackDependencyMode.java",
     "* World Pack dependency strategy.",
     "* World Pack dependency 策略。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/WorldPackDependencyMode.java",
     "* OBSERVE_FAIL: real failure, keep prior path.",
     "* OBSERVE_FAIL：真实 failure，保留 prior path。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/WorldPackDependencyMode.java",
     "* MOCK_CONTINUE: stub/seed continues deeper exploration with MOCK provenance.",
     "* MOCK_CONTINUE：stub/seed 以 MOCK provenance 继续更深探索。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/WorldPackExecutionStage.java",
     "* Stages a single Docker JVM World Pack dependency mode.",
     "* 分阶段执行单个 Docker JVM World Pack dependency mode。"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/WorldPackExecutionStage.java",
     "* are separate stages so deny-all apps can bind HTTP under stubs before honest",
     "* 为独立 stage，使 deny-all 应用在 honest"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/WorldPackExecutionStage.java",
     "* dependency exits are re-run. Selection is stage-driven, never DB-vendor-driven.</p>",
     "* dependency exit 重跑前可在 stub 下绑定 HTTP。选择由 stage 驱动，非 DB-vendor 驱动。</p>"),
    ("src/main/java/com/aq/jvmsentinel/domain/pathdebug/WorldPackManifest.java",
     "* World Pack manifest: profile/env/license/files/schema/seed/dependency stubs (P0-21).",
     "* World Pack manifest：profile/env/license/files/schema/seed/dependency stub（P0-21）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/HardenedRuntimeAttestationGate.java",
     "* Fail-closed enablement gate for gVisor/Kata RuntimeAdapters (P2 SCAFFOLDING).",
     "* gVisor/Kata RuntimeAdapter 的 fail-closed 启用 gate（P2 SCAFFOLDING）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/HardenedRuntimeAttestationGate.java",
     "* hardened capabilities must not be enabled. Even with a present attestation view this",
     "* hardened capability 不得启用。即使有 present attestation view，本"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/HardenedRuntimeAttestationGate.java",
     "* gate never claims production isolation or opens VERIFIED.",
     "* gate 永不声称 production isolation 或打开 VERIFIED。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/HardenedRuntimeAttestationGate.java",
     "     * Attempts to enable a hardened capability. Always fail-closed without attestation.",
     "     * 尝试启用 hardened capability。无 attestation 时始终 fail-closed。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/JsRuntimeAdapter.java",
     "* Second-language RuntimeAdapter skeleton for JavaScript / Node.",
     "* JavaScript / Node 的第二语言 RuntimeAdapter 骨架。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/JsRuntimeAdapter.java",
     "* Default construction declares no observe/probe/launch capabilities; dynamic profiles are",
     "* 默认构造不声明 observe/probe/launch capability；dynamic profile"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/JsRuntimeAdapter.java",
     "* rejected until an independently audited capability set is supplied (ADR-0001).",
     "* 在提供独立审计过的 capability set 前拒绝（ADR-0001）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/JsRuntimeAdapter.java",
     "     * Bind a server-fixed profile only when this adapter actually declares a matching",
     "     * 仅当本 adapter 实际声明匹配"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/JsRuntimeAdapter.java",
     "     * dynamic capability. Static-only adapters reject all dynamic bind attempts.",
     "     * dynamic capability 时绑定服务端固定 profile。仅 static adapter 拒绝所有 dynamic bind 尝试。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/RuntimeAdapter.java",
     "* Out-of-process RuntimeAdapter port (P1-07 skeleton).",
     "* 进程外 RuntimeAdapter port（P1-07 骨架）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/RuntimeAdapter.java",
     "* mount, UID, network or budget overrides. Those fields come only from {@link RuntimeRunProfile}.",
     "* mount、UID、network 或 budget override。这些 field 仅来自 {@link RuntimeRunProfile}。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/RuntimeAdapter.java",
     "     * Bind a server-fixed profile. Implementations must call",
     "     * 绑定服务端固定 profile。实现必须调用"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/RuntimeAdapter.java",
     "     * before any launch.",
     "     * 于任何 launch 之前。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/RuntimeRunProfile.java",
     "* Server-fixed RuntimeAdapter run profile (P1-07).",
     "* 服务端固定的 RuntimeAdapter run profile（P1-07）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/RuntimeRunProfile.java",
     "* by Control Plane registered templates. Model/frontend/Analyzer strings cannot supply them.",
     "* 由 Control Plane 注册 template 提供。Model/frontend/Analyzer 字符串不能提供。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/RuntimeRunProfile.java",
     "     * Factory used by Control Plane templates only.",
     "     * 仅 Control Plane template 使用的 factory。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/RuntimeAdapterOverrideAttempt.java",
     "* Untrusted override attempt from model / frontend / Analyzer.",
     "* 来自 model / frontend / Analyzer 的不可信 override 尝试。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/RuntimeAdapterOverrideAttempt.java",
     "* Any present field must cause fail-closed rejection.",
     "* 任何 present field 必须导致 fail-closed 拒绝。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/SkeletonRuntimeAdapter.java",
     "* Minimal RuntimeAdapter skeleton: binds only server-fixed profiles and rejects overrides.",
     "* 最小 RuntimeAdapter 骨架：仅绑定服务端固定 profile 并拒绝 override。"),
    ("src/main/java/com/aq/jvmsentinel/domain/runtime/SkeletonRuntimeAdapter.java",
     "* Does not launch containers or grant Analyzer dynamic execution rights.",
     "* 不 launch container 也不授予 Analyzer dynamic execution 权限。"),
    ("src/main/java/com/aq/jvmsentinel/domain/security/ProductionFeatures.java",
     "* Fail-closed production session / tenancy feature flags (P2 scaffolding).",
     "* fail-closed 的 production session / tenancy feature flag（P2 scaffolding）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/security/ProductionFeatures.java",
     "* implementation — see {@code docs/adr/0003-production-session-deferred.md}.",
     "* 实现 — 见 {@code docs/adr/0003-production-session-deferred.md}。"),
    ("src/main/java/com/aq/jvmsentinel/domain/universe/ArtifactUniverse.java",
     "* Bounded Artifact Universe: application / third-party / generated / unknown nodes plus",
     "* 有界 Artifact Universe：application / third-party / generated / unknown node 加"),
    ("src/main/java/com/aq/jvmsentinel/domain/universe/ArtifactUniverse.java",
     "* explicit {@link CoverageGap}s (P1-01). Language-neutral; JVM path details live in node ids.",
     "* 显式 {@link CoverageGap}（P1-01）。语言中立；JVM path 细节在 node id。"),
    ("src/main/java/com/aq/jvmsentinel/domain/universe/ArtifactUniverse.java",
     "     * Apply runtime-loaded class diff and return a universe that includes those gaps.",
     "     * 应用 runtime-loaded class diff 并返回包含这些 gap 的 universe。"),
    ("src/main/java/com/aq/jvmsentinel/domain/universe/ArtifactUniverse.java",
     "     * Empty/null runtime list is a no-op.",
     "     * 空/null runtime 列表为 no-op。"),
    ("src/main/java/com/aq/jvmsentinel/domain/universe/ArtifactUniverse.java",
     "     * Minimal hook: diff statically known APPLICATION classes against runtime-loaded names.",
     "     * 最小 hook：diff 静态已知 APPLICATION class 与 runtime-loaded 名。"),
    ("src/main/java/com/aq/jvmsentinel/domain/universe/ArtifactUniverse.java",
     "     * Returns runtime-only and static-not-loaded gaps (bounded).",
     "     * 返回 runtime-only 与 static-not-loaded gap（有界）。"),
    ("src/main/java/com/aq/jvmsentinel/domain/universe/CoverageGap.java",
     "* Explicit analysis / artifact coverage gap. Gaps are never counted as covered.",
     "* 显式 analysis / artifact coverage gap。Gap 永不算 covered。"),
    ("src/main/java/com/aq/jvmsentinel/domain/universe/UniverseScope.java",
     "* Ownership / provenance scope for Artifact Universe nodes (P1-01).",
     "* Artifact Universe node 的 ownership / provenance scope（P1-01）。"),
]

def main():
    n = 0
    for rel, old, new in REPLACEMENTS:
        path = ROOT / rel.replace("/", "\\") if "\\" in str(ROOT) else ROOT / rel
        if not path.exists():
            print(f"MISSING {rel}")
            continue
        text = path.read_text(encoding="utf-8")
        if old not in text:
            # try garbled variant
            garbled = old.replace("—", "—").replace("→", "→")
            if garbled not in text and old.replace("—", "\u2014") not in text:
                print(f"NO MATCH {rel}: {old[:60]}...")
                continue
        if old in text:
            path.write_text(text.replace(old, new, 1), encoding="utf-8")
            n += 1
    print(f"Applied {n} domain replacements")

if __name__ == "__main__":
    main()
