#!/usr/bin/env python3
"""Final pass: fix remaining English-comment heuristic hits."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

MAP: dict[str, str] = {
    # agent
    "* Authorization、Blade-Auth 与 Cookie 为独立通道 — 非空": "* 独立通道：Authorization、Blade-Auth 与 Cookie — 非空",
    "* Batch probe entry. Returns process-style exit codes: 0 ok, 2 all failed, 3 zero events.": "* 批量探测入口。返回进程风格退出码：0 成功，2 全部失败，3 零事件。",
    "* Prefer UNAUTH timeouts (auth discrimination), then other tracks; stable by ordinal; hard cap.": "* 优先 UNAUTH 超时（auth 区分），再其他 track；按序号稳定；硬上限。",
    "* FORCED_REACHABILITY is wire-tracked as ADMIN but must retry before ordinary COVERAGE": "* FORCED_REACHABILITY 在 wire 上记为 ADMIN，但须在普通 COVERAGE",
    "* ADMIN — otherwise Shiro gate-pass PathTraces starve after XSS METHOD_HOP floods.": "* ADMIN 之前重试 — 否则 XSS METHOD_HOP 洪泛后 Shiro gate-pass PathTrace 会饿死。",
    "* Builds the HTTP request head. Authorization and Blade-Auth are independent:": "* 构建 HTTP 请求头。Authorization 与 Blade-Auth 独立：",
    "* neither channel is copied from the other.": "* 任一通道不会从另一通道复制。",
    "* Probe-side entry hit: true when the HTTP response shows the route reached the app or auth": "* 探测侧 entry hit：HTTP 响应显示路由到达 app 或 auth 层时为 true",
    "* layer; false for missing/unsupported methods; absent ({@code null}) for transport failures.": "* 层；缺失/不支持的方法为 false；传输失败时为 absent（{@code null}）。",
    "* Probe alone cannot prove binding success. Only emit false for clear no-route cases.": "* 仅探测无法证明 binding 成功。仅对明确无路由情形 emit false。",
    "// local_address remote_address st ... inode": "// local_address remote_address st ... inode（/proc/net/tcp 列格式）",
    "* Polls one process for LISTEN ports, classifies the first HTTP responder, and writes": "* 轮询单进程的 LISTEN port，分类首个 HTTP 响应者并写入",
    "// Best-effort progress for the GUI.": "// 尽力为 GUI 输出进度。",
    "* VerifyError（StackMapTable）常见于 Druid/Spring auto-config。": "* VerifyError（StackMapTable）常见于 Druid/Spring auto-config 场景。",
    # AutomaticInstrumentation
    "// classPrefix, otherwise auth denials never produce HTTP evidence for the target controller.": "// classPrefix，否则 auth 拒绝永不为目标 controller 产生 HTTP 证据。",
    "// Must allow class-format changes: FilterAdvice FORCED_REACHABILITY uses": "// 须允许 class-format 变更：FilterAdvice FORCED_REACHABILITY 使用",
    "// OnMethodEnter(skipOn=...) to short-circuit recognized auth filters. Branch coverage": "// OnMethodEnter(skipOn=...) 短路已识别 auth filter。Branch coverage",
    "// also requires format changes when enabled. (Previously Advice-only mode called": "// 启用时亦需 format 变更。（此前仅 Advice 模式调用",
    "// disableClassFormatChanges, which silently disabled FORCED skip.)": "// disableClassFormatChanges，静默禁用 FORCED skip。）",
    "// Prefer hierarchy when the servlet API is visible to ByteBuddy's TypePool.": "// 当 servlet API 对 ByteBuddy TypePool 可见时优先 hierarchy。",
    "// Spring Boot fat JARs often hide javax/jakarta.servlet from TypePool, so hasSuperType": "// Spring Boot fat JAR 常对 TypePool 隐藏 javax/jakarta.servlet，hasSuperType",
    "// returns false for DispatcherServlet/Filters even though they are HTTP surfaces.": "// 对 DispatcherServlet/Filter 返回 false，尽管它们是 HTTP surface。",
    "// Explicit Spring MVC surfaces: service() may be inherited, so do not require a local": "// 显式 Spring MVC surface：service() 可继承，勿要求 local",
    "// declaration (getDeclaredMethods misses FrameworkServlet.service on DispatcherServlet).": "// 声明（getDeclaredMethods 会漏 DispatcherServlet 上 FrameworkServlet.service）。",
    "// Shiro / Spring Security filter packages often inherit doFilter; do not require a local": "// Shiro / Spring Security filter 包常继承 doFilter；勿要求 local",
    "// declaration or TypePool servlet hierarchy (fat JARs hide javax/jakarta.servlet).": "// 声明或 TypePool servlet hierarchy（fat JAR 隐藏 javax/jakarta.servlet）。",
    "// Subclasses often override doFilterInternal only; parent doFilter stays on OncePerRequestFilter.": "// 子类常仅 override doFilterInternal；父 doFilter 留在 OncePerRequestFilter。",
    "// Fall through to shape-based advice selection.": "// 继续 shape-based advice 选择。",
    "// preHandle: FORCED may skip body and force true (Blade TokenInterceptor etc.).": "// preHandle：FORCED 可跳过 body 并 force true（Blade TokenInterceptor 等）。",
    "* Returns {@code true} to skip the original filter body after FORCED continues the chain.": "* FORCED 继续 chain 后返回 {@code true} 以跳过原 filter body。",
    "* Non-forced paths return {@code false} (default) so the real filter runs.": "* 非 FORCED 路径返回 {@code false}（默认），使真实 filter 运行。",
    "// Shiro auth filters inherit doFilterInternal from AdviceFilter; Origin #t is the": "// Shiro auth filter 自 AdviceFilter 继承 doFilterInternal；Origin #t 为",
    "// declaring type. Prefer runtime class so LoginFilter / UserFilter are recognized.": "// 声明类型。优先 runtime class 以识别 LoginFilter / UserFilter。",
    "* Spring HandlerInterceptor.preHandle under FORCED: skip original denial and return true.": "* FORCED 下 Spring HandlerInterceptor.preHandle：跳过原拒绝并返回 true。",
    "* Does not elevate VERIFIED; provenance remains INSTRUMENTATION_REACHABILITY.": "* 不提升 VERIFIED；provenance 仍为 INSTRUMENTATION_REACHABILITY。",
    "* P1: Shiro AccessControlFilter.isAccessAllowed (and app LoginFilter overrides) under FORCED.": "* P1：FORCED 下 Shiro AccessControlFilter.isAccessAllowed（及 app LoginFilter override）。",
    "* Skips the original body and forces a {@code true} return; does not continue FilterChain.": "* 跳过原 body 并 force {@code true} 返回；不继续 FilterChain。",
    "// Entering a Spring @*Mapping handler means argument resolution already succeeded.": "// 进入 Spring @*Mapping handler 表示参数解析已成功。",
    "// Spring not on classpath or no active request.": "// classpath 无 Spring 或无 active request。",
    "// Drop XSS/CGLIB flood (kvf HTMLFilter alone burned ~8k events / maxEvents)": "// 丢弃 XSS/CGLIB 洪泛（kvf HTMLFilter 单独消耗 ~8k events / maxEvents）",
    "// so FORCED PathTraces retain Controller→Service→Repository hops.": "// 以便 FORCED PathTrace 保留 Controller→Service→Repository hop。",
    "// Prefer per-request posture header via Spring RequestContextHolder; JVM -D is fallback.": "// 优先经 Spring RequestContextHolder 的 per-request posture header；JVM -D 为 fallback。",
    "// Annotation body reached under FORCED — wall was fail-opened upstream or absent.": "// FORCED 下到达 annotation body — 上游 wall 已 fail-open 或不存在。",
    "* FORCED fail-open for Spring {@code MethodSecurityInterceptor} /": "* Spring {@code MethodSecurityInterceptor} 的 FORCED fail-open /",
    "// Best-effort proceed; leave returned as-is on failure.": "// 尽力 proceed；失败时 returned 保持原样。",
    "// not a request": "// 非 request",
    "// Not a servlet request argument.": "// 非 servlet request 参数。",
    "* Top-level eventType must stay inside AgentJsonlTraceConverter whitelist.": "* 顶层 eventType 须留在 AgentJsonlTraceConverter 白名单内。",
    "* Security nuance (SSRF / JNDI / DESERIALIZATION / multi-kind) goes in": "* 安全细节（SSRF / JNDI / DESERIALIZATION / multi-kind）写入",
    "* pathDebugKind + effectKind / secondaryEffectKinds detail markers.": "* pathDebugKind + effectKind / secondaryEffectKinds 细节标记。",
    "// Remap former NETWORK_* / DNS_* attempt labels onto HTTP_CLIENT + effectKind=SSRF.": "// 将原 NETWORK_* / DNS_* attempt 标签重映射到 HTTP_CLIENT + effectKind=SSRF。",
    "// QLExpress (kvf GenServiceImpl CheckCode) — expression injection sink.": "// QLExpress（kvf GenServiceImpl CheckCode）— expression injection sink。",
    "* Adds a compact hit probe immediately before every JVM conditional branch or switch instruction.": "* 在每个 JVM 条件分支或 switch 指令前添加紧凑 hit probe。",
    "* probe records that the branch site was reached; it does not claim which outgoing edge was taken.</p>": "* probe 记录分支点已到达；不声称走了哪条 outgoing edge。</p>",
    "* Container / infrastructure 排除始终适用。": "* 容器/基础设施排除始终适用。",
    "* control-plane allowlist 为空时，符合 FORCED short-circuit 的已识别": "* control-plane allowlist 为空时，符合 FORCED short-circuit 的已识别",
    "* auth / role / permission / license / feature guard surface。刻意排除": "* auth / role / permission / license / feature guard surface。刻意排除",
    "* infrastructure filter（CORS、encoding、…）。": "* infrastructure filter（CORS、encoding、…）。",
    "* Spring {@code HandlerInterceptor#preHandle} 的 FORCED short-circuit。": "* Spring {@code HandlerInterceptor#preHandle} 的 FORCED 短路。",
    "* Spring method security interceptor（{@code @PreAuthorize} wall）的 FORCED fail-open。": "* Spring method security interceptor（{@code @PreAuthorize} wall）的 FORCED fail-open。",
    "* Subject/SecurityContext；仅 nested auth decision filter 被 short-circuit。": "* Subject/SecurityContext；仅 nested auth decision filter 被短路。",
    "// Observation must not alter the loaded class or grant any capability.": "// Observation 不得改变已加载 class 或授予任何 capability。",
    "* Bounded MySQL classic-protocol substitute for driver startup and harmless query progression.": "* 有界 MySQL classic-protocol 替身，供 driver 启动与无害 query 推进。",
    "* Supported commands are handshake/auth, COM_QUERY, COM_STMT_PREPARE/EXECUTE/CLOSE, ping and quit.": "* 支持 handshake/auth、COM_QUERY、COM_STMT_PREPARE/EXECUTE/CLOSE、ping 与 quit。",
    "* It neither implements SQL semantics nor represents a real MySQL server.": "* 不实现 SQL 语义，也不代表真实 MySQL server。",
    "// Connector/J asks the server for transaction/read-only variables during pool startup.": "// Connector/J 在 pool 启动时向 server 查询 transaction/read-only 变量。",
    "// Empty scalars are not protocol-compatible and fail Druid connection acquisition.": "// 空 scalar 与协议不兼容，会导致 Druid 连接获取失败。",
    "* Bounded Redis RESP2/RESP3 substitute on loopback. It intentionally implements only the": "* loopback 上有界 Redis RESP2/RESP3 替身。有意仅实现",
    "* startup/cache command subset listed in {@link #dispatch(List, Session)} and rejects every": "* {@link #dispatch(List, Session)} 列出的 startup/cache 命令子集，并拒绝所有",
    "* unknown command. It is not a complete Redis implementation or a security boundary.": "* 未知命令。非完整 Redis 实现，亦非 security boundary。",
    "* Under Docker {@code --network none}, Quartz {@code AUTO} instance-id generation often fails with": "* Docker {@code --network none} 下 Quartz {@code AUTO} instance-id 生成常失败，",
    "* When dependency mocks are enabled, force a stable sandbox identity.": "* 启用 dependency mock 时，强制稳定 sandbox identity。",
    "* If the application loads Quartz properties with {@code AUTO}/{@code SYS_PROP}/blank id,": "* 若应用以 {@code AUTO}/{@code SYS_PROP}/blank id 加载 Quartz properties，",
    "* rewrite to a literal sandbox id before {@code StdSchedulerFactory} instantiates.": "* 在 {@code StdSchedulerFactory} 实例化前 rewrite 为 literal sandbox id。",
    # frontend
    "// Keep an explicit selection only; never auto-switch to the first workspace on load.": "// 仅保持显式选择；加载时永不自动切到首个 workspace。",
    "// Results view is not mounted with useAuditLiveRefresh; keep path runs / findings fresh here.": "// Results 视图未挂载 useAuditLiveRefresh；在此保持 path run / finding 新鲜。",
    "// SSE triggers GET reconcile; bounded polling covers stages that emit no scan events.": "// SSE 触发 GET reconcile；有界 polling 覆盖不 emit scan event 的阶段。",
    "// ProbePlan IDENTITY_UNAVAILABLE 步骤；视为决策/分支节点。": "// ProbePlan IDENTITY_UNAVAILABLE 步骤；视为决策/分支节点（ProbePlan）。",
    "* frontend/src/generated/contracts.ts — 导入用于 drift 检查；下方 parser": "* 自 frontend/src/generated/contracts.ts 导入用于 drift 检查；下方 parser",
    "* MVP-6 verified_findings 脚手架。Dashboard 当前返回 []。": "* MVP-6 verified_findings 脚手架；Dashboard 当前返回 []。",
    "// Prefetch coverage + evidence-graph summaries on scan mount so subnav badges": "// scan 挂载时预取 coverage + evidence-graph summary，使 subnav badge",
    "// match EvidenceSummaryStrip without requiring a tab click (GUI_DESIGN §4.1).": "// 与 EvidenceSummaryStrip 一致，无需点击 tab（GUI_DESIGN §4.1）。",
    "// Server coverage matrix only — 0 means no gaps (or not yet loaded).": "// 仅服务端 coverage matrix — 0 表示无 gap（或尚未加载）。",
    "// Evidence graph / coverage matrix removed from workbench chrome; bounce stale deep-links.": "// evidence graph / coverage matrix 已从 workbench chrome 移除；bounce 陈旧 deep-link。",
    "* GENERATED FILE - do not edit by hand.": "* 生成文件 — 请勿手工编辑。",
    "* Source: contracts/schemas (JSON Schema required/properties).": "* 来源：contracts/schemas（JSON Schema required/properties）。",
    "* Regenerated by: scripts/generate-contract-types.ps1 (2026-07-28T07:06:30Z)": "* 由 scripts/generate-contract-types.ps1 重新生成（2026-07-28T07:06:30Z）",
    # analysis main
    "* Dependency port（3306/6379/5432/…）永不作为 application 候选返回。": "* 依赖 port（3306/6379/5432/…）永不作为 application 候选返回。",
    "* PRE_ANALYSIS / dashboard 的确定性 sink 排序。分数为有界启发式，": "* 确定性 sink 排序（PRE_ANALYSIS / dashboard）。分数为有界启发式，",
    "* P0-20：dashboard / report 的 static-first finding 排序。": "* static-first finding 排序（P0-20；dashboard / report）。",
    "// Gate-closed scaffolding 可能出现；勿过度 boost。": "// gate-closed scaffolding 可能出现；勿过度 boost。",
    "* Subject / SecurityContext / StpUtil / getToken 的类型成为 catalog 候选 — runtime 仍由服务端 allowlist gate。": "* Subject / SecurityContext / StpUtil / getToken 类型成为 catalog 候选 — runtime 仍由服务端 allowlist gate。",
    "* exploitability。{@code parse}、{@code read}、": "* exploitability 签名。{@code parse}、{@code read}、",
    "// Flowable / Activiti / Camunda BPMN deploy + expression 面（仅 presence）。": "// Flowable / Activiti / Camunda BPMN deploy + expression 面（仅 presence）。",
    "// Spring Boot File/Launcher 基础设施）会产生噪声、": "// Spring Boot File/Launcher 基础设施）会产生噪声、",
    "* REPORT / PATH / TRIAGE prompt 与服务端的有界 CONTRAST_LEDGER": "* REPORT / PATH / TRIAGE prompt 与服务端有界 CONTRAST_LEDGER",
    "* STATIC_ONLY / unmatched 行永不得叙述为 bypassed/confirmed。": "* STATIC_ONLY / unmatched 行永不得叙述为 bypassed/confirmed。",
    "* unknown / unresolved / truncated / unreached 为 gap，永不算 covered。": "* unknown / unresolved / truncated / unreached 为 gap，永不算 covered。",
    "* AUDIT_FLOW IR2：PathTrace / PathRun observation 后，对当前 scan fact 重跑完整 detector suite": "* AUDIT_FLOW IR2：PathTrace / PathRun observation 后，对当前 scan fact 重跑完整 detector suite",
    "* P2 CONCURRENCY detector：TOCTOU / race / lock-window 启发式。": "* P2 CONCURRENCY detector：TOCTOU / race / lock-window 启发式。",
    "* JWT / crypto / dangerous configuration 启发式（P1-05）。": "* JWT / crypto / dangerous configuration 启发式（P1-05）。",
    "* P1-05 non-taint detector 的独立 recall gate。": "* P1-05 non-taint detector 的独立 recall gate。",
    "*  surfaced artifact class 或 nested framework JAR 中嵌入的 well-known / hardcoded JWT signing key": "* surfaced artifact class 或 nested framework JAR 中嵌入的 well-known / hardcoded JWT signing key",
    "*  surfaced hardcoded rememberMe / cookie-cipher key 为 CONFIG/TYPESTATE hypothesis。": "* surfaced hardcoded rememberMe / cookie-cipher key 为 CONFIG/TYPESTATE hypothesis。",
    "* Key：family + securityProperty + source + effect（case-insensitive）。": "* 合并键：family + securityProperty + source + effect（case-insensitive）。",
    "* P2 STATE detector：cross-request state machine / repeat-submit / quota 启发式。": "* P2 STATE detector：cross-request state machine / repeat-submit / quota 启发式。",
    "// Shiro AccessControl decision filter（isAccessAllowed）— 非外层 chain binder。": "// Shiro AccessControl decision filter（isAccessAllowed）— 非外层 chain binder。",
    "// Container / infra base — 永不 force 外层 chain binder。": "// 容器/infra base — 永不 force 外层 chain binder。",
    "* Forced-only observation 保持有限（node 上 UNREACHED verification）。": "* 仅 FORCED observation 保持有限（node 上 UNREACHED verification）。",
    "* FORCED_REACHABILITY / INSTRUMENTATION_REACHABILITY 单独不能成为 DYNAMIC_CONFIRMED。": "* FORCED_REACHABILITY / INSTRUMENTATION_REACHABILITY 单独不能成为 DYNAMIC_CONFIRMED。",
    "* ProbeTarget.experimentPlanId 须匹配 {@code [A-Za-z0-9_.:/-]{1,128}}。": "* ProbeTarget.experimentPlanId 须匹配 {@code [A-Za-z0-9_.:/-]{1,128}}。",
    "* dynamic probe query/body binding 的有界、charset-safe 样本值。": "* dynamic probe query/body binding 的有界、charset-safe 样本值。",
    "* FRAMEWORK_ADAPTER_CONTEXT 的 well-known / framework HINT note（非 FACT，非 mint）。": "* FRAMEWORK_ADAPTER_CONTEXT 的 well-known / framework HINT note（非 FACT，非 mint）。",
    "// Platform rememberMe cipher dictionary（非 JWT mint 材料）。": "// Platform rememberMe cipher dictionary（非 JWT mint 材料）。",
    "// Fall back: strip legacy「静态推断的…信号」wrapper when present.": "// 回退：存在时剥离 legacy「静态推断的…信号」wrapper。",
    "* FRAMEWORK_ADAPTER_CONTEXT 的 adapter-owned well-known key HINT（非 FACT）。": "* FRAMEWORK_ADAPTER_CONTEXT 的 adapter-owned well-known key HINT（非 FACT）。",
    "// Cookie-channel rememberMe cipher 材料 — 非 JWT；AI 可用 CUSTOM_POC/Cookie。": "// Cookie-channel rememberMe cipher 材料 — 非 JWT；AI 可用 CUSTOM_POC/Cookie。",
    "* rememberMe / cookie-cipher key 面的有界、无 load harvest。": "* rememberMe / cookie-cipher key 面的有界、无 load harvest。",
    "// CookieRememberMeManager 共位 → rememberMe；否则 generic COOKIE 名。": "// CookieRememberMeManager 共位 → rememberMe；否则 generic COOKIE 名。",
    "* harvest rememberMe cipher key 但 encrypted": "* 仅 harvest rememberMe cipher key（encrypted",
    "* rememberMe payload mint 本轮 out of scope。": "* rememberMe payload mint 本轮 out of scope）。",
    "* Bottom-up MethodSummary 骨架：从 call edge seed primitive effect/sanitizer/guard，": "* 自底向上 MethodSummary 骨架：从 call edge seed primitive effect/sanitizer/guard，",
    "* Flowable / BPMN deploy-upload 实验 shape。": "* Flowable / BPMN deploy-upload 实验 shape。",
    "* Spring / Blade annotation shape 的合成 multi-fixture static entry recall 表。": "* Spring / Blade annotation shape 的合成 multi-fixture static entry recall 表。",
    "* Emit {@link com.aq.jvmsentinel.domain.hypothesis.SecurityHypothesis} 候选。": "* 输出 {@link com.aq.jvmsentinel.domain.hypothesis.SecurityHypothesis} 候选。",
    "* Network、command、mount、UID、budget 仍为 control-plane owned。": "* Network、command、mount、UID、budget 仍为 control-plane owned。",
    "* Nested Boot {@code BOOT-INF/lib} jar 展开一层，每 jar 有 class budget；": "* 嵌套 Boot {@code BOOT-INF/lib} jar 展开一层，每 jar 有 class budget；",
    "* Nested BOOT-INF/lib jar 不展开，duplicate 通常来自": "* 嵌套 BOOT-INF/lib jar 不展开，duplicate 通常来自",
    # domain
    "* Control Plane Analyzer ingress：有界 staging → 完整校验 → 原子 evidence 发布。": "* Control Plane Analyzer ingress：有界 staging → 完整校验 → 原子 evidence 发布。",
    "* hypothesis-bound experiment plan 上声明的 expected 或 counter signal。": "* hypothesis-bound experiment plan 上声明的 expected 或 counter signal。",
    "* Entry/Guard/Effect/State/Dependency/Exception 的统一 runtime observation（P1-06）。": "* Entry/Guard/Effect/State/Dependency/Exception 的统一 runtime observation（P1-06）。",
    "* SecurityHypothesis family 分类（ADR-0001 中立 contract）。": "* SecurityHypothesis family 分类（ADR-0001 中立 contract）。",
    "* Evidence Graph edge kind（P1-02）。语言中立；JVM call descriptor 留在 extension。": "* Evidence Graph edge kind（P1-02）。语言中立；JVM call descriptor 留在 extension。",
    "* Auth / ownership / tenant / approval guard。AUTH EntryDto 行与 AUTH_GAP signal": "* Auth / ownership / tenant / approval guard。AUTH EntryDto 行与 AUTH_GAP signal",
    "* Encoding / parameterization / whitelist / reject-branch sanitizer 或 validator。": "* Encoding / parameterization / whitelist / reject-branch sanitizer 或 validator。",
    "* node {@code extensions}，永不进入 ID namespace。": "* node {@code extensions}，永不进入 ID namespace。",
    "* file-type / business state-machine invariant 永不可 force。": "* file-type / business state-machine invariant 永不可 force。",
    "* P0-21 runtime posture kind。Wire IdentityTrack 仍为 UNAUTH/USER/ADMIN/BYPASS_CANDIDATE；": "* P0-21 runtime posture kind。Wire IdentityTrack 仍为 UNAUTH/USER/ADMIN/BYPASS_CANDIDATE；",
    "* Entry/Guard/Effect fact 到 dynamic observation target 的静态桥（P0-21）。": "* Entry/Guard/Effect fact 到 dynamic observation target 的静态桥（P0-21）。",
    "* MOCK_CONTINUE：stub/seed 以 MOCK provenance 继续更深探索。": "* MOCK_CONTINUE：stub/seed 以 MOCK provenance 继续更深探索。",
    "* World Pack manifest：profile/env/license/files/schema/seed/dependency stub（P0-21）。": "* World Pack manifest：profile/env/license/files/schema/seed/dependency stub（P0-21）。",
    "* gVisor/Kata RuntimeAdapter 的 fail-closed 启用 gate（P2 SCAFFOLDING）。": "* gVisor/Kata RuntimeAdapter 的 fail-closed 启用 gate（P2 SCAFFOLDING）。",
    "* TRUSTED_DOCKER / STATIC_ONLY 被拒绝（非 hardened 启用目标）。": "* TRUSTED_DOCKER / STATIC_ONLY 被拒绝（非 hardened 启用目标）。",
    "* Pipeline / job / attempt 编排边界（P1-08 骨架）。": "* Pipeline / job / attempt 编排边界（P1-08 骨架）。",
    "* chat、tool-use、structured-output、context-window 或其他 runtime capability。": "* chat、tool-use、structured-output、context-window 或其他 runtime capability。",
    "* Execd command request。Trusted Docker 以 container 默认 user（通常 root）运行，": "* Execd command request。Trusted Docker 以 container 默认 user（通常 root）运行，",
    "* network-forwarding、host-path、database-connection 或 process-execution 权限。": "* network-forwarding、host-path、database-connection 或 process-execution 权限。",
    # tests - prefix Chinese where needed
    "* P1-01：Artifact Universe scope、nested Boot dependency gap、unresolved dynamic，": "* P1-01：Artifact Universe scope、nested Boot dependency gap、unresolved dynamic，",
    "// P1-01：runtime-loaded class fixture 合并进 scan fact + CoverageMatrix。": "// P1-01：runtime-loaded class fixture 合并进 scan fact + CoverageMatrix。",
    "* Acceptance：workspace audit-history delete 持久化、project-scoped、auth 上 fail-closed。": "* 验收：workspace audit-history delete 持久化、project-scoped、auth 上 fail-closed。",
    "* ALG_NONE、IDENTITY_UNAVAILABLE、AUTH_CONFIRM hypothesis/contrast/insufficient": "* ALG_NONE、IDENTITY_UNAVAILABLE、AUTH_CONFIRM hypothesis/contrast/insufficient",
    "* P1-08：Control Plane query/write port 接受 Test Analyzer 风格 unknown-language node": "* P1-08：Control Plane query/write port 接受 Test Analyzer 风格 unknown-language node",
    "* DYNAMIC_OBSERVATION stage retry：terminal FAILED 允许 retry；leftover QUEUED": "* DYNAMIC_OBSERVATION stage retry：terminal FAILED 允许 retry；leftover QUEUED",
    "* Live JDBC H3 evidence：handshake/meta 不得达 DYNAMIC_CONFIRMED；marker statement 可以。": "* Live JDBC H3 evidence：handshake/meta 不得达 DYNAMIC_CONFIRMED；marker statement 可以。",
    "* authorized Boot-shaped fixture 上 live TRUSTED_DOCKER PathTrace posture acceptance。": "* 在 authorized Boot-shaped fixture 上 live TRUSTED_DOCKER PathTrace posture acceptance。",
    "// ProbeTarget query charset 禁止 raw quote；percent-encode H3 marker。": "// ProbeTarget query charset 禁止 raw quote；percent-encode H3 marker。",
    "* Docker + digest-pinned runtime image 存在时 live path 须成功。": "* Docker + digest-pinned runtime image 存在时 live path 须成功。",
    "// TraceProjectionService request-window 语义）。": "// TraceProjectionService request-window 语义）。",
    "// AES-GCM authentication fail-closed。": "// AES-GCM authentication 失败时 fail-closed。",
    "* P1-05：non-taint detector 骨架 — positive/negative fixture、与 projector merge，": "* P1-05：non-taint detector 骨架 — positive/negative fixture、与 projector merge，",
    "* P2：STATE/CONCURRENCY detector，positive/negative + mutation/holdout DetectorRecallGate": "* P2：STATE/CONCURRENCY detector，positive/negative + mutation/holdout DetectorRecallGate",
    "* P0-02：BLOCKED、cancel、stale QUEUED dynamic、retry 前置/idempotency terminal。": "* P0-02：BLOCKED、cancel、stale QUEUED dynamic、retry 前置/idempotency terminal。",
    "* P2 scaffolding：production session/CSRF/SSO/tenancy/retention 保持 DISABLED。": "* P2 scaffolding：production session/CSRF/SSO/tenancy/retention 保持 DISABLED。",
    "* entry/effect/guard/detector；unload scope 隔离；gate 拒绝 Finding/status 提升。": "* entry/effect/guard/detector；unload scope 隔离；gate 拒绝 Finding/status 提升。",
    "* P1-03：scan build path collect ProviderBundle；DefaultJvmProviders 与 TestOnly": "* P1-03：scan build path collect ProviderBundle；DefaultJvmProviders 与 TestOnly",
    "* P0-14：public schema registry fixture + TS/Java consumer field drift 检查。": "* P0-14：public schema registry fixture + TS/Java consumer field drift 检查。",
    "* extension / x-veyrion-* exception、open kind/family 字符串。": "* extension / x-veyrion-* exception、open kind/family 字符串。",
    "// best-effort": "// 尽力而为",
    "* P0-12：SQL sink + AUTH_GAP 投影为 DATAFLOW + GUARD_COVERAGE hypothesis，无 sink-none。": "* P0-12：SQL sink + AUTH_GAP 投影为 DATAFLOW + GUARD_COVERAGE hypothesis，无 sink-none。",
    "* AUTH / AUTH_CONFIRM → PathRun → report → replay。仅 mock transport 声明 AUDITED；": "* AUTH / AUTH_CONFIRM → PathRun → report → replay。仅 mock transport 声明 AUDITED；",
    "// PathRun stage（mock transport）：seed benign/meta SQL evidence。": "// PathRun stage（mock transport）：seed benign/meta SQL evidence。",
    "// TRIAGE / D3 card identity 来自 PathRun。": "// TRIAGE / D3 card identity 来自 PathRun。",
    "// Replay identity（mock transport cancel + replay accept）。": "// Replay identity（mock transport cancel + replay accept）。",
    "// Report → replay identity：dashboard report/card planId 须匹配 replay。": "// Report → replay identity：dashboard report/card planId 须匹配 replay。",
    "// Re-stage sequence 1 → DUPLICATE_CHUNK（contiguous check 前 containsKey）。": "// Re-stage sequence 1 → DUPLICATE_CHUNK（contiguous check 前 containsKey）。",
    "* MVP-1 acceptance：BRANCH_COVERAGE allowlist、PathRun branchHitMap join、排序、ledger round。": "* MVP-1 验收：BRANCH_COVERAGE allowlist、PathRun branchHitMap join、排序、ledger round。",
    "* Live Docker JAR coverage 经 VEYRION_TEST_ARTIFACT_JAR 仍可选（此处不要求）。": "* Live Docker JAR coverage 经 VEYRION_TEST_ARTIFACT_JAR 仍可选（此处不要求）。",
    "* P0-20：static-first finding 排序降权 UNREACHED / MOCK dynamic 噪声。": "* P0-20：static-first finding 排序降权 UNREACHED / MOCK dynamic 噪声。",
    "* Acceptance：REPORT CONTRAST_LEDGER 强制所有 STATIC_ONLY summary 行（有界）。": "* 验收：REPORT CONTRAST_LEDGER 强制所有 STATIC_ONLY summary 行（有界）。",
    "* Acceptance：static {@code entry:entry-ann-*} 行 join 键为": "* 验收：static {@code entry:entry-ann-*} 行 join 键为",
    "* P0-18：entry × 0-n parameter 编译，含 empty-input rationale。": "* P0-18：entry × 0-n parameter 编译，含 empty-input rationale。",
    "// Bytecode probe gate：sanitizer 非 probe-worthy。": "// Bytecode probe gate：sanitizer 非 probe-worthy。",
    "* P0-21：PathTraceProjector acceptance。": "* P0-21：PathTraceProjector 验收。",
    "* P0-21：PostureExperimentCompiler acceptance。": "* P0-21：PostureExperimentCompiler 验收。",
    "* P0-21：RuntimePostureOrchestrator acceptance。": "* P0-21：RuntimePostureOrchestrator 验收。",
    "* P0-21：TracePlanCompiler acceptance。": "* P0-21：TracePlanCompiler 验收。",
    "* TracePlan vs PathTrace diff acceptance（PATH/TRIAGE 注入 + probe 优先级）。": "* TracePlan vs PathTrace diff 验收（PATH/TRIAGE 注入 + probe 优先级）。",
    "* P0-21：WorldPackPlanner acceptance。": "* P0-21：WorldPackPlanner 验收。",
    "* Acceptance：FORCED ENTRY_HIT  enrich finding wire title/pathRunRef，不提升 VERIFIED。": "* 验收：FORCED ENTRY_HIT enrich finding wire title/pathRunRef，不提升 VERIFIED。",
    "* RememberMe cipher-key detection + Cookie-channel identity 材料（仅 acceptance）。": "* RememberMe cipher-key detection + Cookie-channel identity 材料（仅 acceptance）。",
    "* Acceptance：rememberMe cipher hyp 成为带 STATIC_INFERRED + hypothesisId 的 finding": "* 验收：rememberMe cipher hyp 成为带 STATIC_INFERRED + hypothesisId 的 finding",
    "* Blade JwtProperties default sign-key 在 nested blade-starter-jwt；仅 outer scan 会遗漏": "* Blade JwtProperties default sign-key 在 nested blade-starter-jwt；仅 outer scan 会遗漏",
    "* Synthetic identity harvest/mint 规则：无 silent commercial Blade key fallback": "* Synthetic identity harvest/mint 规则：无 silent commercial Blade key fallback",
    "// MethodSummary / FieldReturn）含 stopReason/budget 诚实 — 非完整 SSA/IFDS/points-to。": "// MethodSummary / FieldReturn）含 stopReason/budget 诚实 — 非完整 SSA/IFDS/points-to。",
    "* P2 SCAFFOLDING：desktop-jlink.ps1 -DryRun 成功路径，fake JDK 提供 jlink。": "* P2 SCAFFOLDING：desktop-jlink.ps1 -DryRun 成功路径，fake JDK 提供 jlink。",
    "* P0-21：path-debug domain contract 往返与 legacy 兼容。": "* P0-21：path-debug domain contract 往返与 legacy 兼容。",
    "* P2 SCAFFOLDING：GVISOR/KATA capability 词汇 + 无 attestation 的 fail-closed 启用。": "* P2 SCAFFOLDING：GVISOR/KATA capability 词汇 + 无 attestation 的 fail-closed 启用。",
    "* P1-24：OpenAI/Anthropic outbound 错误分类、budget bound、disabled kind，": "* P1-24：OpenAI/Anthropic outbound 错误分类、budget bound、disabled kind，",
    "// OpenSandboxException / IllegalArgumentException / SecurityException。": "// OpenSandboxException / IllegalArgumentException / SecurityException。",
    "// fail-closed": "// 失败时 fail-closed",
    "* Digest-pinned TRUSTED_DOCKER runtime image，不可用时空白。": "* Digest-pinned TRUSTED_DOCKER runtime image，不可用时空白。",
    # LoopbackHttpProbe inline English javadoc still in file
    "/** Slightly above 800ms so FORCED past-auth controller work is less often deferred to slow wave. */": "/** 略高于 800ms，使 FORCED 过 auth 后的 controller 工作较少被 defer 到 slow wave。 */",
    "/** Wave-2 budget: recover timed-out high-value / UNAUTH observations. */": "/** Wave-2 预算：恢复超时的高价值 / UNAUTH observation。 */",
    "/** Local sequences inside probe-events.jsonl; the worker renumbers when merging. */": "/** probe-events.jsonl 内本地序号；worker 合并时重新编号。 */",
}


def apply() -> tuple[int, int]:
    touched = 0
    replacements = 0
    roots = [
        ROOT / "src/main/java",
        ROOT / "src/test/java",
        ROOT / "agent/src/main/java",
        ROOT / "frontend/src",
    ]
    for root in roots:
        if not root.exists():
            continue
        for path in root.rglob("*"):
            if path.suffix not in {".java", ".ts", ".tsx"}:
                continue
            rel = path.as_posix().replace(ROOT.as_posix() + "/", "")
            if any(x in "/" + rel for x in ("/ai/", "/control/", "/worker/", "/verification/")):
                continue
            text = path.read_text(encoding="utf-8")
            original = text
            for old, new in MAP.items():
                if old in text:
                    count = text.count(old)
                    text = text.replace(old, new)
                    replacements += count
            if text != original:
                path.write_text(text, encoding="utf-8")
                touched += 1
    return touched, replacements


if __name__ == "__main__":
    t, r = apply()
    print(f"TOUCHED {t} files, {r} replacements")
