#!/usr/bin/env python3
"""Apply resume-phase comment translations from embedded mapping."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Exact comment-line replacements (full line content after indent, as in source)
# Format: English line -> Chinese line (preserve leading // or * spacing from match)
MAP: dict[str, str] = {
    "* It never extracts or executes archive entries.": "* 永不解压或执行 archive entry。",
    "* Dependency ports (3306/6379/5432/…) are never returned as application candidates.": "* Dependency port（3306/6379/5432/…）永不作为 application 候选返回。",
    "// Common Boot default remains a soft candidate for readiness ordering only.": "// 常见 Boot 默认 port 仍仅作为 readiness 排序的 soft 候选。",
    "* Patterns are heuristic and labeled INFERENCE / FLOW_FRAME — never VERIFIED.": "* Pattern 为启发式，标记 INFERENCE / FLOW_FRAME — 永非 VERIFIED。",
    "* not exploitability proof and never alone justify VERIFIED.": "* 非 exploitability 证明，单独永不足以 justify VERIFIED。",
    "* constant-pool and annotation-related structures needed by pre-analysis.": "* pre-analysis 所需的 constant-pool 与 annotation 相关结构。",
    "// Parser defects and malformed lengths must not escape as allocation": "// Parser 缺陷与畸形 length 不得逃逸为 allocation",
    "// requests or turn an invalid class into executable behavior.": "// 请求，也不得将无效 class 变为可执行行为。",
    "* Never opens VERIFIED; max DYNAMIC_SUSPECTED / DYNAMIC_CONFIRMED via server gates.": "* 不打开 VERIFIED；至多 DYNAMIC_SUSPECTED / DYNAMIC_CONFIRMED，经服务端 gate。",
    "// DynamicConfirmedGate remains the only path to DYNAMIC_CONFIRMED.": "// DynamicConfirmedGate 仍是 DYNAMIC_CONFIRMED 的唯一路径。",
    "* P0-20: static-first finding ranking for dashboard / report.": "* P0-20：dashboard / report 的 static-first finding 排序。",
    "* Dynamic failures demote; never invents VERIFIED; never upgrades status.": "* Dynamic failure 降权；永不发明 VERIFIED；永不升级 status。",
    "// Gate-closed scaffolding may appear; do not over-boost.": "// Gate-closed scaffolding 可能出现；勿过度 boost。",
    "// JNDI lookup often implies remote class loading / deserialization side-effects.": "// JNDI lookup 常隐含 remote class loading / deserialization 副作用。",
    "// URLClassLoader loads bytecode from a URL → CLASS_LOADING primary, SSRF secondary.": "// URLClassLoader 从 URL 加载 bytecode → CLASS_LOADING 主、SSRF 次。",
    "// Controllable JDBC URL: network fetch (SSRF), driver feature RCE (COMMAND), driver/class load.": "// 可控 JDBC URL：network fetch（SSRF）、driver feature RCE（COMMAND）、driver/class load。",
    "// JWT / token APIs — presence only; not proof of missing verification or exploitability.": "// JWT / token API — 仅 presence；非 missing verification 或 exploitability 证明。",
    "// Flowable / Activiti / Camunda BPMN deploy + expression surfaces (presence only).": "// Flowable / Activiti / Camunda BPMN deploy + expression 面（仅 presence）。",
    "// Executable Spring Boot archives carry launcher infrastructure outside": "// 可执行 Spring Boot archive 在",
    "// BOOT-INF/classes. Its class loading, archive I/O, and URL handlers are": "// BOOT-INF/classes 外携带 launcher 基础设施。其 class loading、archive I/O 与 URL handler 为",
    "// implementation mechanics rather than application sinks and previously": "// 实现机制而非 application sink，此前",
    "// dominated results for every Boot artifact.": "// 对每个 Boot artifact 的结果占主导。",
    "// P1-03: ensure versioned default providers are installed (thin SPI; discovery stays here).": "// P1-03：确保安装版本化 default provider（薄 SPI；discovery 留在此）。",
    "// Class-name rules are a last-resort fallback for malformed or otherwise": "// Class-name 规则为 malformed 或 otherwise",
    "// unreadable classfiles. Applying them to valid framework classes (for": "// 不可读 classfile 的最后 fallback。应用于有效 framework class（如",
    "// example Spring Boot's File/Launcher infrastructure) produces noisy,": "// Spring Boot File/Launcher 基础设施）会产生噪声、",
    "// unbound pseudo-findings that are not evidence of application behavior.": "// 无 bound 伪 finding，非 application 行为证据。",
    "// Mapped entry without recognizable auth annotation — gap signal only.": "// 无 recognizable auth annotation 的 mapped entry — 仅 gap signal。",
    "* incomplete-ledger enforcement.": "* incomplete-ledger 强制。",
    "* LEGACY convenience: builds ledger via {@link #taintPathsFromSinks}.": "* LEGACY 便利：经 {@link #taintPathsFromSinks} 构建 ledger。",
    "* Production PATH/contrast paths with a static-facts row must pass": "* 带 static-facts 行的 production PATH/contrast 路径必须通过",
    "* LEGACY-only empty-step stubs from sink symbols ({@code tp-sink-*} when no taint-path token).": "* 仅 LEGACY 空 step stub，来自 sink symbol（无 taint-path token 时 {@code tp-sink-*}）。",
    "* Authoritative PATH/contrast must use persisted IR via": "* 权威 PATH/contrast 须经 persisted IR 使用",
    "* this method is only the no-facts-row fallback (coverage={@code LEGACY_INCOMPLETE}).": "* 本方法仅为无 facts-row fallback（coverage={@code LEGACY_INCOMPLETE}）。",
    "// First dynamic coverage observation opens round 1; more covered runs bump the round.": "// 首次 dynamic coverage observation 开启 round 1；更多 covered run 提升 round。",
    "* Ensures every STATIC_ONLY (and unmatched) summary appears in the report text.": "* 确保每个 STATIC_ONLY（及 unmatched）summary 出现在 report 文本。",
    "* If the model omitted them, append a server section and mark incomplete.": "* 若模型遗漏，append 服务端 section 并标记 incomplete。",
    "* plus unbound sinks into static contrast rows (status {@link ContrastStatus#UNKNOWN}": "* 加 unbound sink 为 static contrast 行（status {@link ContrastStatus#UNKNOWN}",
    "* until {@link StaticDynamicContraster} joins PathRuns).": "* 直至 {@link StaticDynamicContraster} join PathRun）。",
    "// AUTH_GAP stays secondary — still project so ledger can show STATIC_ONLY honesty,": "// AUTH_GAP 保持 secondary — 仍投影以便 ledger 显示 STATIC_ONLY 诚实，",
    "// but do not invent taint paths.": "// 但不发明 taint path。",
    "* Runtime projection from persisted scan DTO (no BytecodeFactIndex in store).": "* 从 persisted scan DTO 的 runtime 投影（store 中无 BytecodeFactIndex）。",
    "* Recovers taintPathId from sink.source {@code taint-path=} and evidence": "* 从 sink.source {@code taint-path=} 与 evidence 恢复 taintPathId",
    "// Reconstruct minimal TaintPath stubs from evidence so entryRefs + taintPathId are filled.": "// 从 evidence 重建最小 TaintPath stub，填充 entryRefs + taintPathId。",
    "// Prefer matching sink that references this taint path for category / handler.": "// 优先匹配引用本 taint path 的 sink 以得 category / handler。",
    "// Source handler from annotation evidence on linked entry is resolved later;": "// linked entry 上 annotation evidence 的 source handler 稍后解析；",
    "// leave empty source so projectFromTaint still creates the row via sink loop": "// source 留空以便 projectFromTaint 仍经 sink loop 创建行",
    "// when we only have evidence — emit a stub path with empty source that is": "// 仅 evidence 时 — emit stub path，空 source，",
    "// skipped by empty-handler entry lookup, then sink loop recovers taint-path=.": "// 被 empty-handler entry lookup 跳过，随后 sink loop 恢复 taint-path=。",
    "// When reconstructed paths have placeholder source, prefer sink-source projection only.": "// 重建 path 有 placeholder source 时，仅优先 sink-source 投影。",
    "// Drop placeholder taint stubs — sink.source already carries taint-path=.": "// 丢弃 placeholder taint stub — sink.source 已带 taint-path=。",
    "// AUTH_GAP sinks encode \"Class#method METHOD /route\" in symbol — match declaring class#method.": "// AUTH_GAP sink 在 symbol 编码 \"Class#method METHOD /route\" — 匹配 declaring class#method。",
    "* Joins static contrast rows to PathRuns by {@code entryRef × track}.": "* 按 {@code entryRef × track} 将 static contrast 行 join PathRun。",
    "* never MATCHED and never a bypass-confirmed claim.": "* 永非 MATCHED，永非 bypass-confirmed 声称。",
    "* STATIC_ONLY / unmatched rows must never be narrated as bypassed/confirmed.": "* STATIC_ONLY / unmatched 行永不得叙述为 bypassed/confirmed。",
    "* Returns true when text claims a confirmed bypass for a STATIC_ONLY context.": "* 文本对 STATIC_ONLY 上下文声称 confirmed bypass 时返回 true。",
    "// Stronger match — keep scanning for completeness.": "// 更强 match — 继续扫描以求完整。",
    "// All 401 / AUTH_CHALLENGE — static candidate remains unconfirmed.": "// 全部 401 / AUTH_CHALLENGE — 静态候选仍 unconfirmed。",
    "* A branch hit proves method reachability only; it never proves sink execution or exploitability.": "* branch hit 仅证明 method reachability；永不证明 sink execution 或 exploitability。",
    "* Computes real TP/FP/FN/TN from a CoverageMatrix against baseline ground-truth families.": "* 从 CoverageMatrix 对 baseline ground-truth family 计算真实 TP/FP/FN/TN。",
    "* Metrics are never stub placeholders — suppress/clear of a positive family yields FN and recall failure.": "* Metric 永非 stub placeholder — suppress/clear positive family 产生 FN 与 recall failure。",
    "* Gate: every positive family must be covered (recall == 1 for the positive set)": "* Gate：每个 positive family 须 covered（positive set recall == 1）",
    "* and no negative family may fire. Suppressing a required detector fails this gate.": "* 且 negative family 不得 fire。suppress 必需 detector 则 gate 失败。",
    "* unknown / unresolved / truncated / unreached are gaps and never counted as covered.": "* unknown / unresolved / truncated / unreached 为 gap，永不算 covered。",
    "* Recall gate: baseline expected covered detector families must appear with signals &gt; 0": "* Recall gate：baseline 期望 covered detector family 须 signal &gt; 0 出现",
    "* and countedAsCovered=true. Gaps never satisfy the gate.": "* 且 countedAsCovered=true。Gap 永不满足 gate。",
    "// Sink categories fill families when hypotheses are empty/suppressed for inventory visibility.": "// hypothesis 空/suppress 时 sink category 填充 family 以保 inventory 可见。",
    "// Always expose expected baseline families so suppress mode yields zero-signal gaps.": "// 始终暴露期望 baseline family，使 suppress mode 产生 zero-signal gap。",
    "// Incomplete universe is an unknown/gap signal (not covered).": "// Incomplete universe 为 unknown/gap signal（非 covered）。",
    "* P2 CONCURRENCY detector: TOCTOU / race / lock-window heuristics.": "* P2 CONCURRENCY detector：TOCTOU / race / lock-window 启发式。",
    "* Does not elevate verification status; resource open/close typestate remains": "* 不提升 verification status；resource open/close typestate 仍",
    "* Declared AUDITED for heuristic recall (positive/negative/holdout); not a real race prover.": "* 声明 AUDITED 用于启发式 recall（positive/negative/holdout）；非真实 race prover。",
    "* JWT / crypto / dangerous configuration heuristics (P1-05).": "* JWT / crypto / dangerous configuration 启发式（P1-05）。",
    "* Reuses AUTH_GAP/JWT sink signals and redacted configuration lines; never invents sink-none.": "* 复用 AUTH_GAP/JWT sink signal 与 redacted configuration 行；永不发明 sink-none。",
    "// Reuse JWT sink presence as CONFIG family signal (not DATAFLOW / not sink-none).": "// 复用 JWT sink presence 为 CONFIG family signal（非 DATAFLOW / 非 sink-none）。",
    "* Skeleton: flags well-known risky dependency name/version patterns from ArtifactUniverse.": "* Skeleton：从 ArtifactUniverse 标记 well-known  risky dependency name/version pattern。",
    "* Skeleton: projects DESERIALIZATION sinks into CONFIG/TYPESTATE-adjacent hypotheses": "* Skeleton：将 DESERIALIZATION sink 投影为 CONFIG/TYPESTATE-adjacent hypothesis",
    "* without inventing fake dataflow sink-none rows.": "* 不发明 fake dataflow sink-none 行。",
    "// Also surface enableDefaultTyping / polymorphic typing hints from config.": "// 亦从 config surface enableDefaultTyping / polymorphic typing hint。",
    "* Detectors emit {@link SecurityHypothesis} only — never elevate verification status.": "* Detector 仅 emit {@link SecurityHypothesis} — 永不提升 verification status。",
    "* Bounded scan facts available to non-taint detectors. Configuration lines are": "* non-taint detector 可用的有界 scan fact。Configuration 行",
    "* already redacted by {@code ArtifactMetadataReader}.": "* 已由 {@code ArtifactMetadataReader} redact。",
    "* Independent recall gate for P1-05 non-taint detectors.": "* P1-05 non-taint detector 的独立 recall gate。",
    "* Removing a detector that owns an expected securityProperty must fail the gate.": "* 移除拥有期望 securityProperty 的 detector 须使 gate 失败。",
    "* Passes when every expected securityProperty appears at least once in {@code hypotheses}.": "* 每个期望 securityProperty 在 {@code hypotheses} 至少出现一次则 pass。",
    "* Runs {@code registry} against {@code context} and evaluates expected properties.": "* 对 {@code context} 运行 {@code registry} 并评估期望 property。",
    "* Detects guard dominance / auth annotation inconsistency within a declaring class:": "* 检测 declaring class 内 guard dominance / auth annotation 不一致：",
    "* some mapped entries declare guards while sibling entries on the same class do not.": "* 部分 mapped entry 声明 guard 而同 class sibling 未声明。",
    "* Does not restate AUTH_GAP as sink-none; emits GUARD_INCONSISTENCY hypotheses.": "* 不以 sink-none 重述 AUTH_GAP；emit GUARD_INCONSISTENCY hypothesis。",
    "// Nested optional.": "// Nested 可选。",
    "* Surfaces hardcoded rememberMe / cookie-cipher keys as CONFIG/TYPESTATE hypotheses.": "*  surfaced hardcoded rememberMe / cookie-cipher key 为 CONFIG/TYPESTATE hypothesis。",
    "* Not a Fastjson / generic DESERIALIZATION sink projection — category is cipher-key config.": "* 非 Fastjson / 通用 DESERIALIZATION sink 投影 — category 为 cipher-key config。",
    "// Config/evidence fallback when artifact path is unavailable (tests / legacy).": "// artifact path 不可用时的 config/evidence fallback（test / legacy）。",
    "// Primary signal remains setCipherKey; dictionary labels are secondary.": "// 主 signal 仍为 setCipherKey；dictionary label 为 secondary。",
    "* Merges projector and detector hypotheses with stable dedupe.": "* 以稳定 dedupe 合并 projector 与 detector hypothesis。",
    "* Key: family + securityProperty + source + effect (case-insensitive).": "* Key：family + securityProperty + source + effect（case-insensitive）。",
    "* Heuristic IDOR/BOLA ownership gap: object-id PathVariable/RequestParam on an HTTP": "* 启发式 IDOR/BOLA ownership gap：HTTP entry 上 object-id PathVariable/RequestParam",
    "* entry without ownership / tenant / principal-binding preconditions.": "* 无 ownership / tenant / principal-binding 前置条件。",
    "* Skeleton: resource open without close in the same caller (FILE_READ / stream constructors).": "* Skeleton：同一 caller 内 open 无 close（FILE_READ / stream constructor）。",
    "// Fallback from sink catalog FILE_READ when IR edges unavailable.": "// IR edge 不可用时从 sink catalog FILE_READ fallback。",
    "* P2 STATE detector: cross-request state machine / repeat-submit / quota heuristics.": "* P2 STATE detector：cross-request state machine / repeat-submit / quota 启发式。",
    "* Emits {@link HypothesisFamily#STATE} candidates only — never elevates verification status.": "* 仅 emit {@link HypothesisFamily#STATE} 候选 — 永不提升 verification status。",
    "* Declared AUDITED for heuristic recall (positive/negative/holdout); not a full state-machine solver.": "* 声明 AUDITED 用于启发式 recall；非完整 state-machine solver。",
    "* Classifies entry protocols so unknown / WebSocket surfaces stay UNREACHED": "* 分类 entry protocol，使 unknown / WebSocket 面保持 UNREACHED",
    "* instead of being mislabeled as HTTP probe targets.": "* 而非误标为 HTTP probe target。",
    "* Deterministic; models must not author these defaults.": "* 确定性；模型不得撰写这些 default。",
    "* without changing {@link ApiDtos.PathRunDto} Jackson round-trip.": "* 不改变 {@link ApiDtos.PathRunDto} Jackson round-trip。",
    "// Flatten UI-facing PathTrace fields onto PathRun so GUI parsers need not dig nested.": "// 将 UI 向 PathTrace field 扁平化到 PathRun，GUI parser 无需 dig nested。",
    "// Keep wire shape stable for GUI parsers that expect arrays.": "// 保持 wire shape 稳定，供期望 array 的 GUI parser。",
    "* Forced-only observations stay limited (UNREACHED verification on nodes).": "* Forced-only observation 保持有限（node 上 UNREACHED verification）。",
    "* Suggestions are advisory only — server still compiles and authorizes ExperimentPlans.": "* 建议仅为 advisory — 服务端仍编译并授权 ExperimentPlan。",
    "* FORCED_REACHABILITY / INSTRUMENTATION_REACHABILITY cannot alone become DYNAMIC_CONFIRMED.": "* FORCED_REACHABILITY / INSTRUMENTATION_REACHABILITY 单独不能成为 DYNAMIC_CONFIRMED。",
    "// preserve effects observed before truncation": "// 保留 truncation 前观测的 effect",
    "* ProbeTarget.experimentPlanId must match {@code [A-Za-z0-9_.:/-]{1,128}}.": "* ProbeTarget.experimentPlanId 须匹配 {@code [A-Za-z0-9_.:/-]{1,128}}。",
    "* Entry ids can be long route keys — hash the overflow instead of failing registration.": "* Entry id 可为长 route key — 对 overflow hash 而非 registration 失败。",
    "* Projects PathRun-like facts into a unified RuntimeObservation and marks": "* 将 PathRun-like fact 投影为统一 RuntimeObservation 并标记",
    "* minimal incremental detector subjects (P1-06).": "* 最小增量 detector subject（P1-06）。",
    "* Failed / empty projection: successfulProjection=false, lifecycle must not change.": "* 失败/空 projection：successfulProjection=false，lifecycle 不得变更。",
    "// GUARD_DIFF maps AUTH_CHALLENGE → GUARD_DENY (counter); other kinds keep AUTH_CHALLENGE.": "// GUARD_DIFF 映射 AUTH_CHALLENGE → GUARD_DENY（counter）；其他 kind 保持 AUTH_CHALLENGE。",
    "* P0-21: server-owned runtime posture decisions. AI/frontend cannot supply forced reachability policy.": "* P0-21：服务端 owned runtime posture 决策。AI/frontend 不能提供 forced reachability policy。",
    "* BYPASS posture is generated only for AUTH PoC candidates or UNAUTH unexpected pass-through.": "* BYPASS posture 仅对 AUTH PoC 候选或 UNAUTH unexpected pass-through 生成。",
    "* P0-21: plan World Pack manifests for OBSERVE_FAIL and MOCK_CONTINUE dependency strategies.": "* P0-21：为 OBSERVE_FAIL 与 MOCK_CONTINUE dependency 策略规划 World Pack manifest。",
    "* Resolves the Docker JVM dependency mode for the <em>exploration</em> stage": "* 解析 <em>exploration</em> stage 的 Docker JVM dependency mode",
    "* so deny-all jars can bind HTTP under protocol-agnostic stubs before probes run.": "* 使 deny-all jar 在 probe 运行前可在 protocol-agnostic stub 下绑定 HTTP。",
    "* use {@link #resolveRuntimeDependencyMode(Iterable, WorldPackExecutionStage)} with": "* 使用 {@link #resolveRuntimeDependencyMode(Iterable, WorldPackExecutionStage)} 与",
    "* Stage-driven World Pack mode for one Docker JVM. Mode follows execution stage only;": "* 单 Docker JVM 的 stage 驱动 World Pack mode。Mode 仅随 execution stage；",
    "* posture mix and database vendor must not select the mode.": "* posture mix 与 database vendor 不得选择 mode。",
    "* SPI for optional framework-specific route / auth <em>hints</em>.": "* 可选 framework 特定 route / auth <em>hint</em> 的 SPI。",
    "* Adapters contribute signals only; the control plane, identity mint path, and AUTH": "* Adapter 仅贡献 signal；control plane、identity mint path 与 AUTH",
    "* pipeline remain JVM-generic and must not treat any single framework as first-class.": "* pipeline 保持 JVM-generic，不得将任一 framework 视为 first-class。",
    "* When true, probes may dual-write a secondary auth header channel in addition to": "* 为 true 时，probe 除",
    "* Suggested secondary HTTP header name (e.g. {@code Blade-Auth}) when": "* 建议次要 HTTP header 名（如 {@code Blade-Auth}）当",
    "* Optional adapter-owned detection dictionary for known weak / historical sign-key": "* 可选 adapter-owned detection dictionary，用于 known weak / historical sign-key",
    "* strings. Used only when the same bytes appear inside the authorized artifact;": "* 字符串。仅当相同字节出现在 authorized artifact 内时使用；",
    "* never a silent mint source. Classification remains RULE_GENERATED / HINT.": "* 永非 silent mint source。Classification 保持 RULE_GENERATED / HINT。",
    "* Additional archive path fragments that hint this adapter's auth surface": "* 提示本 adapter auth 面的额外 archive path 片段",
    "* Optional redacted harvest signal for dashboard/AI. Must not return raw commercial": "* 可选 redacted harvest signal 供 dashboard/AI。不得返回 raw commercial",
    "* defaults as if they were FACT; prefer {@link #jwtSecretHintNotes()} for HINT inject.": "* default 当作 FACT；HINT 注入优先 {@link #jwtSecretHintNotes()}。",
    "* Well-known / framework HINT notes for FRAMEWORK_ADAPTER_CONTEXT (not FACT, not mint).": "* FRAMEWORK_ADAPTER_CONTEXT 的 well-known / framework HINT note（非 FACT，非 mint）。",
    "* Registry of {@link FrameworkAdapter} implementations.": "* {@link FrameworkAdapter} 实现的 registry。",
    "* contribute the same SPI signals when they match. Test-only adapters may be injected.": "* 匹配时贡献相同 SPI signal。可注入仅 test adapter。",
    "// Platform rememberMe cipher dictionary (not JWT mint material).": "// Platform rememberMe cipher dictionary（非 JWT mint 材料）。",
    "* Secondary auth header name from the first matched adapter that prefers one;": "* 来自首个 prefer 的 matched adapter 的次要 auth header 名；",
    "* empty when none.": "* 无则为空。",
    "// Preserve prior generic high-value tokens used by ProbePlanService.": "// 保留 ProbePlanService 先前使用的 generic 高价值 token。",
    "* Second FrameworkAdapter skeleton for Servlet/Filter surfaces (P2 SCAFFOLDING).": "* Servlet/Filter 面的第二 FrameworkAdapter 骨架（P2 SCAFFOLDING）。",
    "* invent FACT, or enable WAR dynamic execution by itself.": "* 发明 FACT，或自行启用 WAR dynamic execution。",
    "* Optional thin SpringBlade / BladeX adapter — contributes route/class signals and a": "* 可选薄 SpringBlade / BladeX adapter — 贡献 route/class signal 与",
    "* secondary-header HINT ({@code Blade-Auth}) like any other FrameworkAdapter.": "* 次要 header HINT（{@code Blade-Auth}），同其他 FrameworkAdapter。",
    "* Not a first-class product path; control plane / identity / AUTH stay JVM-generic.": "* 非 first-class 产品路径；control plane / identity / AUTH 保持 JVM-generic。",
    "* Well-known aliases are HINT-only via {@link #jwtSecretHintNotes()} / {@link #wellKnownSecretHints()};": "* Well-known alias 仅 HINT，经 {@link #jwtSecretHintNotes()} / {@link #wellKnownSecretHints()}；",
    "* AI must call {@code code_query} to harvest material from the authorized artifact.": "* AI 须调用 {@code code_query} 从 authorized artifact harvest 材料。",
    "* Historical Blade/JwtProperties commercial default — adapter detection dictionary only.": "* 历史 Blade/JwtProperties commercial default — 仅 adapter detection dictionary。",
    "* Do not treat as FACT or mint unless harvested from the artifact.": "* 除非从 artifact harvest，否则不作 FACT 或 mint。",
    "// Framework HINT: this adapter's surface typically dual-channels a secondary auth header.": "// Framework HINT：本 adapter 面通常双 channel 次要 auth header。",
    "// Library order for AI; DEFAULT_SECRET_HS256 only mintable after harvest.": "// AI 的 library 顺序；DEFAULT_SECRET_HS256 仅 harvest 后可 mint。",
    "* Default Spring MVC adapter — always matches as the JVM-generic baseline.": "* 默认 Spring MVC adapter — 始终作为 JVM-generic baseline 匹配。",
    "* Does not prefer a secondary auth header; HS256 minting requires artifact harvest.": "* 不 prefer 次要 auth header；HS256 mint 需 artifact harvest。",
    "// Do not include bare \"controller\" — nearly every Spring MVC class matches and starves probe budget.": "// 勿包含裸 \"controller\" — 几乎每 Spring MVC class 都匹配并耗尽 probe budget。",
    "* WAR-oriented FrameworkAdapter skeleton (P2 SCAFFOLDING).": "* WAR 向 FrameworkAdapter 骨架（P2 SCAFFOLDING）。",
    "* Dynamic execution remains {@link RunProfile#MODE_WAR_DYNAMIC_DISABLED} until a future": "* Dynamic execution 保持 {@link RunProfile#MODE_WAR_DYNAMIC_DISABLED} 直至未来",
    "* audited embedded-container profile lands — this adapter never grants host execution.": "* 审计过的 embedded-container profile 落地 — 本 adapter 永不授予 host execution。",
    "* Neutral dynamic-policy fact for WAR: profile presence does not enable host execution.": "* WAR 的中性 dynamic-policy fact：profile 存在不启用 host execution。",
    "* Attach FORCED / COVERAGE PathRun materials to finding wire without elevating": "* 将 FORCED / COVERAGE PathRun 材料 attach 到 finding wire，不提升",
    "// Preserve prior server-gated elevations; enricher never upgrades into them.": "// 保留先前服务端 gate 提升；enricher 永不升级进入。",
    "// ADMIN track alone is ambiguous (COVERAGE and FORCED share it) — require plan/trace.": "// 仅 ADMIN track 歧义（COVERAGE 与 FORCED 共享）— 要求 plan/trace。",
    "* Project selected high-signal non-taint detector hypotheses into findings so UI/report": "* 将选定高信号 non-taint detector hypothesis 投影为 finding，使 UI/report",
    "* are not sink-only. Always {@link ApiDtos#STATIC_INFERRED}; never DYNAMIC_CONFIRMED/VERIFIED.": "* 非仅 sink。始终 {@link ApiDtos#STATIC_INFERRED}；永非 DYNAMIC_CONFIRMED/VERIFIED。",
    "* Merge sink-projected findings with selected detector-hypothesis findings (append-only).": "* 合并 sink 投影 finding 与选定 detector-hypothesis finding（仅 append）。",
    "* kept as a fixture/compat alias — not a core mint source.": "* 作为 fixture/compat alias 保留 — 非 core mint source。",
    "* Redacted candidate for AI / tool output. Never carries raw secret bytes.": "* AI / tool 输出的 redacted 候选。永不携带 raw secret 字节。",
    "*                       RULE_GENERATED when alias matched a well-known dictionary": "*                       alias 匹配 well-known dictionary 时为 RULE_GENERATED",
    "*                       entry found in the artifact; HINT for adapter-only notes": "*                       artifact 中找到 entry；adapter-only note 为 HINT",
    "* Compact constructor for callers that omit secondary header name / materials.": "* 省略次要 header 名 / 材料的 caller 用的紧凑 constructor。",
    "* Adapter-owned well-known key HINTs for FRAMEWORK_ADAPTER_CONTEXT (not FACT).": "* FRAMEWORK_ADAPTER_CONTEXT 的 adapter-owned well-known key HINT（非 FACT）。",
    "// Cookie-channel rememberMe cipher material — not JWT; AI may use CUSTOM_POC/Cookie.": "// Cookie-channel rememberMe cipher 材料 — 非 JWT；AI 可用 CUSTOM_POC/Cookie。",
    "// Prefer adapters whose path signals appear in this evidence blob.": "// 优先 path signal 出现在本 evidence blob 的 adapter。",
    "* Channel-agnostic identity material harvested from an authorized artifact.": "* 从 authorized artifact harvest 的 channel-agnostic identity 材料。",
    "* Never elevates verification status; value bytes stay internal to mint/apply paths.": "* 不提升 verification status；value 字节留在 mint/apply path 内部。",
    "* Neutral identity-material kinds. Framework names are never required fields —": "* 中性 identity-material kind。Framework 名永非必填 field —",
    "* adapters/harvesters may cite them only in provenance notes.": "* adapter/harvester 仅在 provenance note 引用。",
    "* Bounded, load-free harvest of rememberMe / cookie-cipher key surfaces.": "* rememberMe / cookie-cipher key 面的有界、无 load harvest。",
    "* harvested as cipher material. Well-known default dictionaries only <em>label</em> weak": "* harvest 为 cipher 材料。Well-known default dictionary 仅 <em>label</em> weak",
    "* keys — they are not a detection gate.": "* key — 非 detection gate。",
    "* Unquoted Base64 with non-alphabet boundaries so {@code setCipherKey2AvV…} does not": "* 非 alphabet 边界的 unquoted Base64，使 {@code setCipherKey2AvV…} 不",
    "* swallow the method name into the candidate.": "* 将 method 名吞入 candidate。",
    "// Primary gate: setCipherKey must appear in this entry.": "// 主 gate：setCipherKey 须出现在本 entry。",
    "// CookieRememberMeManager co-location → rememberMe; otherwise generic COOKIE name.": "// CookieRememberMeManager 共位 → rememberMe；否则 generic COOKIE 名。",
    "// Canonical AES key Base64 lengths (16-byte / 32-byte) with padding.": "// 规范 AES key Base64 长度（16-byte / 32-byte）含 padding。",
    "// Other padded lengths: require +/ or digit to cut classpath / identifier noise.": "// 其他 padded 长度：要求 +/ 或 digit 以 cut classpath / identifier 噪声。",
    "* Platform-owned synthetic identity materials harvested from the authorized artifact.": "* 从 authorized artifact harvest 的平台 owned synthetic identity 材料。",
    "* Provenance is MOCK / RULE_GENERATED / FACT (config in JAR); never claimed as operator credentials.": "* Provenance 为 MOCK / RULE_GENERATED / FACT（JAR 内 config）；永非 operator credential。",
    "* cipher / session materials produce Cookie headers. There is no silent fallback to commercial": "* cipher / session 材料产生 Cookie header。无 silent fallback 到 commercial",
    "* framework defaults for arbitrary JARs, and rememberMe cipher keys are never used as JWT secrets.": "* framework default（任意 JAR），rememberMe cipher key 永不用作 JWT secret。",
    "* Marker Cookie value when a rememberMe cipher key was harvested but encrypted": "* harvest rememberMe cipher key 但 encrypted",
    "* rememberMe payload minting is out of scope this round.": "* rememberMe payload mint 本轮 out of scope。",
    "* Fallback materialization for known technique labels when the AI PoC did not": "* AI PoC 未",
    "* supply authorizationHeader. Prefer AI-authored PoC material when present.": "* 提供 authorizationHeader 时，已知 technique label 的 fallback materialization。存在时优先 AI 撰写 PoC 材料。",
    "// Probe layer prefixes \"Authorization: bearer \"; a single space yields an empty-ish token.": "// Probe 层前缀 \"Authorization: bearer \"；单空格产生近乎空 token。",
    "* Minimal HS256 JWT with generic enterprise-ish claims (sub/role/exp).": "* 带 generic enterprise-ish claim（sub/role/exp）的最小 HS256 JWT。",
    "* Framework-specific claim shapes belong in AI-authored PoCs or adapter hints —": "* Framework 特定 claim shape 属于 AI 撰写 PoC 或 adapter hint —",
    "* not hardcoded as the platform mint narrative.": "* 非 hardcode 为 platform mint 叙事。",
    "* Secondary auth-channel value: scheme + token (probe layer does not auto-prefix": "* 次要 auth-channel 值：scheme + token（probe 层不 auto-prefix",
    "* the secondary header name). Wire/API still may call this via {@link #bladeAuthHeaderValue}.": "* 次要 header 名）。Wire/API 仍可通过 {@link #bladeAuthHeaderValue} 调用。",
    "* Compatible projection of existing scan facts into a minimal {@link EvidenceGraph}.": "* 现有 scan fact 到最小 {@link EvidenceGraph} 的兼容投影。",
    "* Does not mutate {@link StaticFactSnapshot} persistence; reads only.": "* 不 mutate {@link StaticFactSnapshot} persistence；仅读。",
    "// Guarantee finding evidence refs are joinable on at least one node.": "// 保证 finding evidence ref 至少在一个 node 可 join。",
    "// entrypointRef may be id or route; prefer entry: prefix when it looks like an id.": "// entrypointRef 可为 id 或 route；像 id 时优先 entry: 前缀。",
    "* Builds a bounded, serializable CFG from method IR sites.": "* 从 method IR site 构建有界、可序列化 CFG。",
    "* Uses callEdges / memberAccesses / resolved call-graph evidence as block anchors;": "* 以 callEdges / memberAccesses / resolved call-graph evidence 为 block anchor；",
    "* does not claim full branch or exception fidelity.": "* 不声称完整 branch 或 exception fidelity。",
    "// Annotate call-site adjacency without inventing targets outside observed blocks.": "// 标注 call-site adjacency，不发明 observed block 外 target。",
    "// Fall back to the first method that owns observed sites matching the needle.": "// Fallback 到拥有匹配 needle 的 observed site 的首个 method。",
    "* Serializable method CFG projection built from persisted IR sites.": "* 从 persisted IR site 构建的可序列化 method CFG 投影。",
    "* Not a full SSA form; branch/exception edges may be incomplete.": "* 非完整 SSA；branch/exception edge 可能不完整。",
    "* Bounded field / return taint enhancement hooks over existing {@link BytecodeFactIndex.TaintPath}s.": "* 现有 {@link BytecodeFactIndex.TaintPath} 上的有界 field / return taint 增强 hook。",
    "* Does not replace {@code InterproceduralTaintAnalyzer}; it annotates paths with FIELD/RETURN/SANITIZER steps.": "* 不替换 {@code InterproceduralTaintAnalyzer}；以 FIELD/RETURN/SANITIZER step 标注 path。",
    "// Field-read bridge: if a later CALL step's method reads a field written by source method.": "// Field-read bridge：若后续 CALL step 的 method 读 source method 写的 field。",
    "* Projects IR / sink / guard heuristics into MethodSummary and sanitizer seeds.": "* 将 IR / sink / guard 启发式投影为 MethodSummary 与 sanitizer seed。",
    "* Provenance is inference only; never FACT or verification elevation.": "* Provenance 仅 inference；永非 FACT 或 verification 提升。",
    "* Bounded method summary used for bottom-up effect/guard/sanitizer propagation.": "* 用于 bottom-up effect/guard/sanitizer 传播的有界 method summary。",
    "* Provenance is inference; never a FACT upgrade.": "* Provenance 为 inference；永非 FACT 升级。",
    "* Bottom-up MethodSummary skeleton: seed primitive effects/sanitizers/guards from call edges,": "* Bottom-up MethodSummary 骨架：从 call edge seed primitive effect/sanitizer/guard，",
    "* then propagate custom effects to callers of summarized callees (wrapper pattern).": "* 再将 custom effect 传播到 summarized callee 的 caller（wrapper pattern）。",
    "// Seed from the method's own identity (IR/sink/guard heuristics), not only callees.": "// 从 method 自身 identity（IR/sink/guard 启发式）seed，不仅 callee。",
    "// Conservative: any parameter may influence a value-returning callee result used by caller.": "// 保守：任一 parameter 可能影响 caller 使用的 value-returning callee 结果。",
    "// Bottom-up: wrappers that call summarized effectful callees inherit custom effects.": "// Bottom-up：调用 summarized effectful callee 的 wrapper 继承 custom effect。",
    "// Controllable JDBC URL is SSRF/RCE/classload — not SQL injection.": "// 可控 JDBC URL 为 SSRF/RCE/classload — 非 SQL injection。",
    "// Conservative name heuristics for app wrappers that look like sinks.": "// 像 sink 的 app wrapper 的保守 name 启发式。",
    "* Minimal known sanitizer / validator markers for kernel summaries and taint hooks.": "* kernel summary 与 taint hook 的最小 known sanitizer / validator marker。",
    "* Matching is declarative only; it does not prove runtime neutralization.": "* Matching 仅 declarative；不证明 runtime neutralization。",
    "* Optional thin AnalysisPack for SpringBlade-like JWT credential experiment shapes": "* 可选薄 AnalysisPack，SpringBlade-like JWT credential 实验 shape",
    "* the alias for fixture alignment only.": "* alias 仅 fixture 对齐。",
    "* P0-15: selectable open-source practical recall samples.": "* P0-15：可选开源 practical recall sample。",
    "* Artifacts are never vendored; local digests are optional. Without a local JAR,": "* Artifact 永不 vendored；local digest 可选。无 local JAR 时，",
    "* scoring returns {@code NOT_EVALUABLE} and must not be claimed as production recall.": "* scoring 返回 {@code NOT_EVALUABLE}，不得声称 production recall。",
    "* Resolve optional local artifact under a samples root directory.": "* 在 samples root 目录下解析可选 local artifact。",
    "* Prefers {@link Sample#artifactGlob()} matches, skips wrapper/sources/javadoc jars,": "* 优先 {@link Sample#artifactGlob()} 匹配，跳过 wrapper/sources/javadoc jar，",
    "* prefers larger bootable jars under {@code target/}, and breaks ties by path.": "* 优先 {@code target/} 下更大 bootable jar，path 打破平局。",
    "* Synthetic multi-fixture static entry recall table for Spring / Blade annotation shapes.": "* Spring / Blade annotation shape 的合成 multi-fixture static entry recall 表。",
    "* This is a development baseline, not a production recall claim. 5/5 fixture scores must": "* 此为 development baseline，非 production recall 声称。5/5 fixture 分数",
    "* never be marketed as real-world recall.": "* 永不得 marketed 为 real-world recall。",
    "* Base contract for versioned analysis providers. Providers emit IR/hypothesis": "* 版本化 analysis provider 的基础 contract。Provider emit IR/hypothesis",
    "* contributions only; they must not write Findings or elevate verification status.": "* contribution 仅；不得写 Finding 或提升 verification status。",
    "* Emits {@link com.aq.jvmsentinel.domain.hypothesis.SecurityHypothesis} candidates.": "* Emit {@link com.aq.jvmsentinel.domain.hypothesis.SecurityHypothesis} 候选。",
    "* Must not write Findings or elevate verification status.": "* 不得写 Finding 或提升 verification status。",
    "* Emits server-gated {@link com.aq.jvmsentinel.model.ExperimentPlan} shapes.": "* Emit 服务端 gate 的 {@link com.aq.jvmsentinel.model.ExperimentPlan} shape。",
    "* Network, command, mount, UID, and budget remain control-plane owned.": "* Network、command、mount、UID、budget 仍为 control-plane owned。",
    "* Hard caps applied by {@link ProviderOutputGate} before contributions are accepted.": "* {@link ProviderOutputGate} 在 accept contribution 前应用 hard cap。",
    "* Scope-bound context for provider collection. Wrong-scope contributions fail closed.": "* provider collection 的 scope-bound context。错误 scope contribution fail-closed。",
    "* Typed provider outputs. Finding writes and verification elevation are rejected by the gate.": "* 类型化 provider 输出。Finding 写与 verification 提升被 gate 拒绝。",
    "* Detector output is a {@link SecurityHypothesis} candidate only — never a Finding,": "* Detector 输出仅为 {@link SecurityHypothesis} 候选 — 永非 Finding，",
    "* and lifecycle is clamped to {@link HypothesisLifecycle#CANDIDATE} by the gate.": "* lifecycle 由 gate 钳制为 {@link HypothesisLifecycle#CANDIDATE}。",
    "* Validates provider outputs: schema, scope, budget, dedupe.": "* 校验 provider 输出：schema、scope、budget、dedupe。",
    "* Rejects Finding writes and verification-status elevation.": "* 拒绝 Finding 写与 verification-status 提升。",
    "// Force CANDIDATE — providers cannot elevate lifecycle / write Finding.": "// 强制 CANDIDATE — provider 不能提升 lifecycle / 写 Finding。",
    "* Process-local registry of versioned analysis providers.": "* 版本化 analysis provider 的进程内 registry。",
    "* Collect routes all outputs through {@link ProviderOutputGate}.": "* Collect 将所有输出路由经 {@link ProviderOutputGate}。",
    "* Unregisters a provider. Only contributions from its {@link AnalysisProvider#declaredScope()}": "* 注销 provider。仅其 {@link AnalysisProvider#declaredScope()} 的 contribution",
    "* disappear on the next {@link #collect(ProviderContext)}; other providers are unaffected.": "* 在下次 {@link #collect(ProviderContext)} 消失；其他 provider 不受影响。",
    "* Collect contributions from all registered providers, gated by schema/scope/budget/dedupe.": "* 从所有注册 provider collect contribution，经 schema/scope/budget/dedupe gate。",
    "* Providers cannot write Findings; status elevation is clamped/rejected.": "* Provider 不能写 Finding；status 提升被钳制/拒绝。",
    "* Thin default JVM providers wrapping existing PreAnalysis / sink / AuthCoverage /": "* 包装现有 PreAnalysis / sink / AuthCoverage / 的薄 default JVM provider",
    "* AnalysisPack logic. No big-bang rewrite of discovery.": "* AnalysisPack 逻辑。discovery 无 big-bang 重写。",
    "* P2 scaffolding EntryProvider for Servlet / Filter surfaces.": "* Servlet / Filter 面的 P2 scaffolding EntryProvider。",
    "* Returns empty when no interface/superclass/fixture class-name hit.": "* 无 interface/superclass/fixture class-name hit 时返回空。",
    "* Builds a bounded {@link ArtifactUniverse} from archive layout + {@link BytecodeFactIndex}.": "* 从 archive layout + {@link BytecodeFactIndex} 构建有界 {@link ArtifactUniverse}。",
    "* Nested Boot {@code BOOT-INF/lib} jars are expanded one layer with a per-jar class budget;": "* Nested Boot {@code BOOT-INF/lib} jar 展开一层，每 jar 有 class budget；",
    "* deeper nesting and budget hits become explicit {@link CoverageGap}s.": "* 更深 nesting 与 budget hit 成为显式 {@link CoverageGap}。",
    "// Ensure fact-index classes not seen in archive walk still appear (e.g. path quirks).": "// 确保 archive walk 未见 fact-index class 仍出现（如 path quirk）。",
    "// Gaps are expected coverage honesty signals; incomplete only means budget/IO/analysis stop.": "// Gap 为期望 coverage 诚实 signal；incomplete 仅意味 budget/IO/analysis stop。",
    "* Same binary class name under distinct archive paths → MULTI_VERSION_CLASS gap.": "* 不同 archive path 下相同 binary class 名 → MULTI_VERSION_CLASS gap。",
    "* Nested BOOT-INF/lib jars are not expanded, so duplicates are typically from": "* Nested BOOT-INF/lib jar 不展开，duplicate 通常来自",
    "* BOOT-INF/classes plus a root/META duplicate or repeated class entries.": "* BOOT-INF/classes 加 root/META duplicate 或重复 class entry。",
    "* One-layer expand: enumerate .class entries inside a nested Boot/WEB-INF lib jar.": "* 一层展开：枚举 nested Boot/WEB-INF lib jar 内 .class entry。",
    "* Does not open jars nested inside that jar. Class budgets produce explicit gaps.": "* 不打开该 jar 内 nested jar。Class budget 产生显式 gap。",
    "// fall through": "// 穿透",
    "* CI gate runner for curated main-style acceptance tests.": "* 精选 main-style acceptance test 的 CI gate runner。",
    "* Fails closed when zero tests execute or zero assertions are recorded.": "* 零 test 执行或零 assertion 记录时 fail-closed。",
    "* Curated P0 gate: coordinator-first for fast signal, then persistence and lifecycle.": "* 精选 P0 gate：coordinator 优先快速 signal，再 persistence 与 lifecycle。",
    "* P0-14 / P1-08 architecture dependency gates.": "* P0-14 / P1-08 架构 dependency gate。",
    "* P1-08: new code must not introduce control → analysis.parser reverse dependency.": "* P1-08：新代码不得引入 control → analysis.parser 反向依赖。",
    "* Scans control, application, and adapter trees; zero exceptions allowed.": "* 扫描 control、application、adapter 树；零 exception 允许。",
    "// best-effort cleanup": "// 尽力 cleanup",
    "// fail-closed": "// fail-closed",
    # acceptance tests batch
    "* P1-01: Artifact Universe scopes, nested Boot dependency gaps, unresolved dynamics,": "* P1-01：Artifact Universe scope、nested Boot dependency gap、unresolved dynamic，",
    "* coverage matrix summary, and runtime diff hook.": "* coverage matrix 摘要与 runtime diff hook。",
    "// P1-01: runtime-loaded class fixture merges into scan facts + CoverageMatrix.": "// P1-01：runtime-loaded class fixture 合并进 scan fact + CoverageMatrix。",
    "// Duplicate application class under a second archive path → MULTI_VERSION_CLASS gap.": "// 第二 archive path 下 duplicate application class → MULTI_VERSION_CLASS gap。",
    "// The bounded HTTP body reader may close the connection before": "// 有界 HTTP body reader 可能在",
    "// a response when a client exceeds the request hard limit.": "// client 超过 request hard limit 时关闭连接而无 response。",
    "* Acceptance: workspace audit-history delete persists, is project-scoped, and fails closed on auth.": "* Acceptance：workspace audit-history delete 持久化、project-scoped、auth 上 fail-closed。",
    "* CRUD UX only — does not invent VERIFIED claims.": "* 仅 CRUD UX — 不发明 VERIFIED 声称。",
    "// Bare scans have empty child tables; delete must not require 1-row child DELETEs.": "// 裸 scan 子表为空；delete 不得要求 1-row 子 DELETE。",
    "// Former 409 SCAN_ACTIVE case: stuck QUEUED worker task must cancel-then-delete → 204.": "// 原 409 SCAN_ACTIVE：卡住 QUEUED worker task 须 cancel-then-delete → 204。",
    "* Verifies server-owned audit pipeline advancement with run/stage/expected-resource identity.": "* 验证服务端 owned audit pipeline 推进与 run/stage/expected-resource identity。",
    "* P1-21: AUTH identity-track fail-closed contrasts for MISSING_AUTH, empty Bearer,": "* P1-21：MISSING_AUTH、空 Bearer 等的 AUTH identity-track fail-closed 对比，",
    "* ALG_NONE, IDENTITY_UNAVAILABLE, and AUTH_CONFIRM hypothesis/contrast/insufficient": "* ALG_NONE、IDENTITY_UNAVAILABLE、AUTH_CONFIRM hypothesis/contrast/insufficient",
    "* three-state (fixture; not live Docker production orchestration).": "* 三态（fixture；非 live Docker production orchestration）。",
    "// AI-authored empty bearer literal must stay on bypass track, not collapse to MISSING_AUTH.": "// AI 撰写空 bearer literal 须 stay bypass track，不 collapse 到 MISSING_AUTH。",
    "// AUTH_CONFIRM distinction: challenge alone never upgrades verification.": "// AUTH_CONFIRM 区分：仅 challenge 永不升级 verification。",
    "* AUTH_CONFIRM three-state: HYPOTHESIS / DYNAMIC_CONTRAST / INSUFFICIENT_EVIDENCE.": "* AUTH_CONFIRM 三态：HYPOTHESIS / DYNAMIC_CONTRAST / INSUFFICIENT_EVIDENCE。",
    "* Fixture-only; never elevates to VERIFIED.": "* 仅 fixture；永不提升到 VERIFIED。",
    "* P0-14: migration order + pinned checksum consistency (UTF-8 content, same as persistence)": "* P0-14：migration 顺序 + pinned checksum 一致性（UTF-8 内容，同 persistence）",
    "// Sample: persistence class still lists the same migration resource names in order.": "// 示例：persistence class 仍按序列出相同 migration resource 名。",
    "* Allowed paths mode: empty changed set → skip OK; out-of-allowlist path → fail semantics.": "* Allowed paths mode：空 changed set → skip OK；allowlist 外 path → fail 语义。",
    "* P1-08: Control Plane query/write ports accept Test Analyzer-style unknown-language nodes": "* P1-08：Control Plane query/write port 接受 Test Analyzer 风格 unknown-language node",
    "* and expose findings / PathRuns / providers / createScan projection via application.port": "* 并经 application.port 暴露 finding / PathRun / provider / createScan 投影",
    "* without JVM-only required fields.": "* 无 JVM-only 必填 field。",
    "* Declared scope = incremental port decoupling, not a ControlPlaneServer big-bang rewrite.": "* 声明 scope = 增量 port 解耦，非 ControlPlaneServer big-bang 重写。",
    "// baseUri is /api/v1 without trailing slash — must concatenate, not URI.resolve.": "// baseUri 为 /api/v1 无 trailing slash — 须 concatenate，非 URI.resolve。",
    "// Strip additive columns so V018/V019 re-apply cleanly on the V001 base tables.": "// 剥离 additive column，使 V018/V019 在 V001 base table 上干净 re-apply。",
    "// Column absent on older shapes.": "// 旧 shape 上 column 缺失。",
    "* P0-13: Coverage Matrix projection honesty, checksum stability, and recall-gate skeleton.": "* P0-13：Coverage Matrix 投影诚实、checksum 稳定与 recall-gate 骨架。",
    "* P0-13 mutation/holdout: compute real TP/FP/FN from CoverageMatrix vs baseline groundTruth.": "* P0-13 mutation/holdout：从 CoverageMatrix 对 baseline groundTruth 计算真实 TP/FP/FN。",
    "* Suppressing a required detector must fail the recall gate (FN &gt; 0).": "* Suppress 必需 detector 须使 recall gate 失败（FN &gt; 0）。",
    "// Live fixture should surface SQL + AUTH_GAP detector families when present.": "// Live fixture 存在时应 surface SQL + AUTH_GAP detector family。",
    "* P0-10 residual: Controller handler binds to repository-layer sink via persisted taint paths.": "* P0-10 残余：Controller handler 经 persisted taint path 绑定 repository-layer sink。",
    "* Stage retry for DYNAMIC_OBSERVATION: terminal FAILED allows retry; leftover QUEUED is": "* DYNAMIC_OBSERVATION stage retry：terminal FAILED 允许 retry；leftover QUEUED",
    "* superseded; focus-probe stays fail-closed busy while a live task exists.": "* 被 supersede；live task 存在时 focus-probe 保持 fail-closed busy。",
    "* Acceptance for P0-01 single-entry focus-probe API:": "* P0-01 单 entry focus-probe API 的 acceptance：",
    "* unauthorized → 403, authorized → 202 DYNAMIC_SUSPECTED, idempotent replay → 200, busy → 409.": "* 未授权 → 403，已授权 → 202 DYNAMIC_SUSPECTED，幂等 replay → 200，busy → 409。",
    "// First task remains QUEUED (no worker), so a second key must fail closed busy.": "// 首 task 仍 QUEUED（无 worker），第二 key 须 fail-closed busy。",
    "* P1-02: Evidence Graph projection, finding evidence-ref join, AUTH EntryDto gap, API bound.": "* P1-02：Evidence Graph 投影、finding evidence-ref join、AUTH EntryDto gap、API bound。",
    "// Bidirectional: node → findingIds via shared evidence refs.": "// 双向：经共享 evidence ref 的 node → findingIds。",
    "// P1-02: authoritative graph persisted in StaticFactSnapshot (schema v4).": "// P1-02：权威 graph 持久化于 StaticFactSnapshot（schema v4）。",
    "// Bidirectional live: finding → node and node → findingId.": "// 双向 live：finding → node 与 node → findingId。",
    "* P1-23: responsive / long-text layout contract — TS + CSS declare max-width,": "* P1-23：响应式/长文本 layout contract — TS + CSS 声明 max-width，",
    "* overflow, and word-break rules for narrow viewports.": "* overflow 与 word-break 规则供窄 viewport。",
    "* Audited scope = contract tests (not manual visual regression).": "* 审计 scope = contract test（非手动 visual regression）。",
    "* P1-23: GUI semantics contract — download labels, results views, and Worker/BLOCKED": "* P1-23：GUI 语义 contract — download label、results view 与 Worker/BLOCKED",
    "* status text stay consistent with GUI_DESIGN (asserted against frontend sources).": "* status 文本与 GUI_DESIGN 一致（对 frontend source 断言）。",
    "// Subnav badges must prefetch on scan mount (not only after tab click).": "// Subnav badge 须在 scan mount 预取（非仅 tab 点击后）。",
    "* P1-06: hypothesis-driven ExperimentPlan kinds, server default candidates, and lifecycle gate.": "* P1-06：hypothesis 驱动 ExperimentPlan kind、服务端 default 候选与 lifecycle gate。",
    "// Factory is server-owned (no model): same inputs → same plan ids.": "// Factory 服务端 owned（无 model）：相同 input → 相同 plan id。",
    "// Failed / empty projection must not change lifecycle.": "// 失败/空 projection 不得变更 lifecycle。",
    "// Successful expected signal → SUPPORTED + incremental subjects.": "// 成功 expected signal → SUPPORTED + incremental subject。",
    "// Already SUPPORTED cannot be re-elevated / contradicted by another observation.": "// 已 SUPPORTED 不能被另一 observation re-elevate / contradict。",
    "// Counter signal on another hypothesis → CONTRADICTED.": "// 另一 hypothesis 上 counter signal → CONTRADICTED。",
    "// Gate never invents VERIFIED / DYNAMIC_CONFIRMED lifecycle values.": "// Gate 永不发明 VERIFIED / DYNAMIC_CONFIRMED lifecycle 值。",
    "* P1-06 wiring: PathRun success via {@link ControlPlaneStore#replacePathRunsForTask}": "* P1-06 接线：PathRun 成功经 {@link ControlPlaneStore#replacePathRunsForTask}",
    "* failed PathRuns do not.": "* 失败 PathRun 不。",
    "// Failed PathRun (empty evidence) must not change lifecycle.": "// 失败 PathRun（空 evidence）不得变更 lifecycle。",
    "// Successful expected ENTRY_HIT → SUPPORTED via replacePathRunsForTask callback.": "// 成功 expected ENTRY_HIT → SUPPORTED，经 replacePathRunsForTask callback。",
    "// Counter signal via AUTH_CHALLENGE on GUARD_DIFF → CONTRADICTED.": "// GUARD_DIFF 上 AUTH_CHALLENGE counter signal → CONTRADICTED。",
    "// Must not invent VERIFIED / DYNAMIC_CONFIRMED on hypothesis lifecycle.": "// hypothesis lifecycle 上不得发明 VERIFIED / DYNAMIC_CONFIRMED。",
    "* Live JDBC H3 evidence: handshake/meta must not reach DYNAMIC_CONFIRMED; marker statement can.": "* Live JDBC H3 evidence：handshake/meta 不得达 DYNAMIC_CONFIRMED；marker statement 可以。",
    "* Embedded SQLite JDBC always runs. Postgres container path runs when Docker + image available;": "* Embedded SQLite JDBC 始终运行。Docker + image 可用时 Postgres container path 运行；",
    "* otherwise SKIP with log (gate still PASS).": "* 否则 SKIP 并 log（gate 仍 PASS）。",
    "// SQLite may reject unterminated quote; statement text still observed.": "// SQLite 可能拒绝 unterminated quote；statement 文本仍被观测。",
    "// Handshake/meta analogue: server readiness noise must not confirm.": "// Handshake/meta 类比：server readiness 噪声不得 confirm。",
    "// Marker SQL may fail at the engine; H3 cares about observed statement text.": "// Marker SQL 可能在 engine 失败；H3 关心观测 statement 文本。",
    "* Manual Docker demo: kvf Shiro JAR under FORCED_REACHABILITY + session seed.": "* 手动 Docker demo：FORCED_REACHABILITY + session seed 下 kvf Shiro JAR。",
    "* Always releases retained sandboxes in {@code finally}. Not a VERIFIED claim.": "* 始终在 {@code finally} 释放 retained sandbox。非 VERIFIED 声称。",
    "// Prefer QLExpress expression-injection surface (exact /generator/check/code).": "// 优先 QLExpress expression-injection 面（精确 /generator/check/code）。",
    "// Always include one UNAUTH twin for contrast when present.": "// 存在时始终包含一个 UNAUTH twin 作对比。",
    "* Live TRUSTED_DOCKER PathTrace posture acceptance on an authorized Boot-shaped fixture.": "* authorized Boot-shaped fixture 上 live TRUSTED_DOCKER PathTrace posture acceptance。",
    "* Asserts UNAUTH / COVERAGE_POSTURE / FORCED_REACHABILITY experiment plans execute and": "* 断言 UNAUTH / COVERAGE_POSTURE / FORCED_REACHABILITY experiment plan 执行且",
    "* PathRun wire carries path-debug fields without elevating VERIFIED.": "* PathRun wire 携带 path-debug field，不提升 VERIFIED。",
    "* Docker/image unavailable → SKIP with fixture-free compile-time contract still recorded.": "* Docker/image 不可用 → SKIP，仍记录无 fixture compile-time contract。",
    "// Path-debug enrichment is best-effort when projection succeeds; at minimum": "// projection 成功时 path-debug enrichment 尽力而为；至少",
    "// experimentPlanId from posture plans must appear on at least one PathRun.": "// posture plan 的 experimentPlanId 须出现在至少一个 PathRun。",
    "* Manual demo (not gate): scan a vulnerable Boot-shaped JAR end-to-end and print": "* 手动 demo（非 gate）：端到端 scan 脆弱 Boot-shaped JAR 并打印",
    "* static findings + live PathTrace / verification outcomes after P0-21 wiring fixes.": "* P0-21 接线修复后的 static finding + live PathTrace / verification outcome。",
    "// Prefer control-plane registration (exploration stage → MOCK_CONTINUE).": "// 优先 control-plane 注册（exploration stage → MOCK_CONTINUE）。",
    "// Re-bind with SQLi-focused probes while keeping resolved World Pack mode.": "// 保持 resolved World Pack mode 时用 SQLi 聚焦 probe 重绑。",
    "// best-effort: demo must not leave veyrion-trusted-* containers": "// 尽力：demo 不得留下 veyrion-trusted-* 容器",
    "* Prefer /search probes and stamp META_MARKER query for H3-style observation.": "* 优先 /search probe 并 stamp META_MARKER query 供 H3 风格 observation。",
    "// ProbeTarget query charset forbids raw quotes; percent-encode the H3 marker.": "// ProbeTarget query charset 禁止 raw quote；percent-encode H3 marker。",
    "// Cross-method call chain for sensor hops (Controller→Service→Repo pattern).": "// sensor hop 的 cross-method call chain（Controller→Service→Repo 模式）。",
    "* Live TRUSTED_DOCKER multi-request evidence: ≥2 HTTP probes, PathRun correlation isolation.": "* Live TRUSTED_DOCKER 多 request evidence：≥2 HTTP probe、PathRun correlation 隔离。",
    "* Docker unavailable / runtime image missing → explicit SKIP (gate still PASS via fixture asserts).": "* Docker 不可用 / runtime image 缺失 → 显式 SKIP（gate 经 fixture assert 仍 PASS）。",
    "* When Docker + digest-pinned runtime image are present, the live path must succeed.": "* Docker + digest-pinned runtime image 存在时 live path 须成功。",
    "// Interleave JDBC→HTTP per correlation. Batching all JDBC before any HTTP drains": "// 每 correlation 交错 JDBC→HTTP。全部 JDBC 批在任何 HTTP 前",
    "// the pending window on the first HTTP and orphans later correlations (current": "// 在首 HTTP 耗尽 pending window 并 orphan 后续 correlation（当前",
    "// TraceProjectionService request-window semantics).": "// TraceProjectionService request-window 语义）。",
    "// Request-window semantics: pending JDBC is drained at each HTTP. Interleaved": "// Request-window 语义：每次 HTTP 耗尽 pending JDBC。交错",
    "// JDBC→HTTP per correlation keeps isolation under the current projector.": "// 每 correlation JDBC→HTTP 在当前 projector 下保持隔离。",
    "// Strict SQL ownership only when this PathRun carries correlationId.": "// 仅本 PathRun 带 correlationId 时严格 SQL ownership。",
    "// Fixture path covers isolation; live Agent may omit corr today.": "// Fixture path 覆盖隔离；live Agent 今日可能 omit corr。",
    "// Docker bind mounts can briefly keep the managed JAR locked on Windows.": "// Docker bind mount 在 Windows 上可能短暂锁定 managed JAR。",
    "// AES-GCM authentication fails closed.": "// AES-GCM authentication fail-closed。",
    "* P1-05: non-taint detector skeleton — positive/negative fixtures, merge with projector,": "* P1-05：non-taint detector 骨架 — positive/negative fixture、与 projector merge，",
    "* no sink-none AUTH representation, AcceptanceTestRunner gate.": "* 无 sink-none AUTH 表示，AcceptanceTestRunner gate。",
    "// Independent remove-detector → fail proofs for the first-batch trio.": "// 独立 remove-detector → 首批 trio 的 fail 证明。",
    "* P2: STATE/CONCURRENCY detectors with positive/negative + mutation/holdout DetectorRecallGate": "* P2：STATE/CONCURRENCY detector，positive/negative + mutation/holdout DetectorRecallGate",
    "* and Servlet/WebFlux/Listener/Scheduled/WebSocket EntryProvider scaffolding.": "* 与 Servlet/WebFlux/Listener/Scheduled/WebSocket EntryProvider scaffolding。",
    "// Windows may keep the SQLite WAL briefly locked after close.": "// Windows 可能在 close 后短暂锁定 SQLite WAL。",
    "* P0-02: BLOCKED, cancel, stale QUEUED dynamic, and retry prerequisite/idempotency terminals.": "* P0-02：BLOCKED、cancel、stale QUEUED dynamic、retry 前置/idempotency terminal。",
    "// Hang until interrupted so cancel always races ahead of provider completion.": "// Hang 直至 interrupt，使 cancel 总在 provider 完成前 race。",
    "* Read-only GET helper: retries only transient {@code 409 PERSISTENCE_REJECTED}": "* 只读 GET helper：仅重试 transient {@code 409 PERSISTENCE_REJECTED}",
    "* P2 scaffolding: production session/CSRF/SSO/tenancy/retention remain DISABLED.": "* P2 scaffolding：production session/CSRF/SSO/tenancy/retention 保持 DISABLED。",
    "* P1-03: versioned Provider SPI — defaults wrap PreAnalysis; TestOnly can add": "* P1-03：版本化 Provider SPI — default 包装 PreAnalysis；TestOnly 可添加",
    "* entry/effect/guard/detector; unload is scope-isolated; gate rejects Finding/status elevation.": "* entry/effect/guard/detector；unload scope 隔离；gate 拒绝 Finding/status 提升。",
    "* P1-03: scan build path collects ProviderBundle; DefaultJvmProviders and TestOnly": "* P1-03：scan build path collect ProviderBundle；DefaultJvmProviders 与 TestOnly",
    "* contributions are authoritative entry/effect/guard sources merged into the scan.": "* contribution 为合并进 scan 的权威 entry/effect/guard source。",
    "// Unload TestOnly: a new scan must not retain that provider's scope.": "// Unload TestOnly：新 scan 不得保留该 provider scope。",
    "// Wrong scope must fail closed.": "// 错误 scope 须 fail-closed。",
    "* P0-14: public schema registry fixtures + TS/Java consumer field drift check.": "* P0-14：public schema registry fixture + TS/Java consumer field drift 检查。",
    "* Uses a lightweight hand validator (no new JSON Schema dependency).": "* 使用轻量 hand validator（无新 JSON Schema 依赖）。",
    "* Minimal object validator: required, closed enums, additionalProperties with": "* 最小 object validator：required、closed enum、additionalProperties 与",
    "* extensions / x-veyrion-* exceptions, open kind/family strings.": "* extension / x-veyrion-* exception、open kind/family 字符串。",
    "// Shared wire names that must not drift from schema optional/required sets.": "// 共享 wire 名不得与 schema optional/required 集 drift。",
    "* P2: second-language static LanguageAnalyzer + RuntimeAdapter skeleton.": "* P2：第二语言静态 LanguageAnalyzer + RuntimeAdapter 骨架。",
    "* Proves non-JVM IR reuses the same store/hypothesis/coverage/GUI degrade path,": "* 证明 non-JVM IR 复用相同 store/hypothesis/coverage/GUI degrade path，",
    "* and that static analyzer support does not grant dynamic RuntimeAdapter capability.": "* 且 static analyzer 支持不授予 dynamic RuntimeAdapter capability。",
    "// Even an explicitly capability-bearing adapter still rejects untrusted overrides.": "// 即使显式 capability-bearing adapter 仍拒绝不可信 override。",
    "* P0-12: SQL sink + AUTH_GAP project to DATAFLOW + GUARD_COVERAGE hypotheses without sink-none.": "* P0-12：SQL sink + AUTH_GAP 投影为 DATAFLOW + GUARD_COVERAGE hypothesis，无 sink-none。",
    "* P1-20: single-entry debug baseline with fixture strategy + mock-transport identity chain": "* P1-20：fixture 策略 + mock-transport identity chain 的单 entry debug baseline",
    "* AUTH / AUTH_CONFIRM → PathRun → report → replay. Declared AUDITED for mock transport only;": "* AUTH / AUTH_CONFIRM → PathRun → report → replay。仅 mock transport 声明 AUDITED；",
    "* no live Docker; VERIFIED remains closed.": "* 无 live Docker；VERIFIED 保持关闭。",
    "// AUTH stage (mock): plan accepted for fixed entry × UNAUTH track.": "// AUTH stage（mock）：固定 entry × UNAUTH track 接受 plan。",
    "// PathRun stage (mock transport): seed benign/meta SQL evidence.": "// PathRun stage（mock transport）：seed benign/meta SQL evidence。",
    "// H3 may confirm; VERIFIED must never appear.": "// H3 可 confirm；VERIFIED 永不得出现。",
    "// TRIAGE / D3 card identity from PathRuns.": "// TRIAGE / D3 card identity 来自 PathRun。",
    "// Replay identity (mock transport cancel + replay accept).": "// Replay identity（mock transport cancel + replay accept）。",
    "// Report → replay identity: dashboard report/card planId must match replay.": "// Report → replay identity：dashboard report/card planId 须匹配 replay。",
    "// AUTH_CONFIRM three-state gate (mock): hypothesis / contrast / insufficient.": "// AUTH_CONFIRM 三态 gate（mock）：hypothesis / contrast / insufficient。",
    "// AUTH contrast codes remain classifiable without live Docker.": "// AUTH contrast code 无 live Docker 仍可分类。",
    "* P1-07: out-of-process Analyzer / Runtime contract — same-process Fake regression plus a": "* P1-07：进程外 Analyzer / Runtime contract — 同进程 Fake regression 加",
    "* real {@link ProcessBuilder} subprocess {@link com.aq.jvmsentinel.domain.analyzer.TestAnalyzerProcessMain}": "* 真实 {@link ProcessBuilder} 子进程 {@link com.aq.jvmsentinel.domain.analyzer.TestAnalyzerProcessMain}",
    "* that submits minimal IR through {@link AnalyzerIngress}.": "* 经 {@link AnalyzerIngress} 提交最小 IR。",
    "* Real subprocess: ProcessBuilder launches {@link TestAnalyzerProcessMain}; parent ingests": "* 真实子进程：ProcessBuilder launch {@link TestAnalyzerProcessMain}；父进程 ingest",
    "* the written chunk envelope through AnalyzerIngress (out-of-process contract proof).": "* 经 AnalyzerIngress 的 written chunk envelope（进程外 contract 证明）。",
    "// Commit path: wrong scope identity (includes artifact) fails closed as SCOPE_MISMATCH.": "// Commit path：错误 scope identity（含 artifact）fail-closed 为 SCOPE_MISMATCH。",
    "// Server does not allow PROGRAM_IR in this scenario": "// 本场景服务端不允许 PROGRAM_IR",
    "// Manifest claims both chunks but only chunk0 staged": "// Manifest 声称两 chunk 但仅 chunk0 staged",
    "// Re-stage sequence 1 → DUPLICATE_CHUNK (containsKey before contiguous check).": "// Re-stage sequence 1 → DUPLICATE_CHUNK（contiguous check 前 containsKey）。",
    "// Replay on a new session after prior publish — same submissionId": "// 先前 publish 后新 session replay — 相同 submissionId",
    "// Drop ingress/analyzer; store still serves history": "// 丢弃 ingress/analyzer；store 仍服务 history",
    "* Optional real-artifact smoke: set VEYRION_BALDEX_JAR to a SpringBlade/baldex executable JAR.": "* 可选真实 artifact smoke：设 VEYRION_BALDEX_JAR 为 SpringBlade/baldex 可执行 JAR。",
    "* Skips cleanly when unset so default CI does not require the sample.": "* 未设时干净 SKIP，默认 CI 不要求 sample。",
    "* MVP-1 acceptance: BRANCH_COVERAGE allowlist, PathRun branchHitMap join, ranking, ledger round.": "* MVP-1 acceptance：BRANCH_COVERAGE allowlist、PathRun branchHitMap join、排序、ledger round。",
    "* Live Docker JAR coverage remains optional via VEYRION_TEST_ARTIFACT_JAR (not required here).": "* Live Docker JAR coverage 经 VEYRION_TEST_ARTIFACT_JAR 仍可选（此处不要求）。",
    "* P0-20: static-first finding ranking demotes UNREACHED / MOCK dynamic noise.": "* P0-20：static-first finding 排序降权 UNREACHED / MOCK dynamic 噪声。",
    "* Acceptance: REPORT CONTRAST_LEDGER forces all STATIC_ONLY summary rows (bounded).": "* Acceptance：REPORT CONTRAST_LEDGER 强制所有 STATIC_ONLY summary 行（有界）。",
    "// Model omits STATIC_ONLY → server appends + REPORT_LEDGER_INCOMPLETE.": "// 模型遗漏 STATIC_ONLY → 服务端 append + REPORT_LEDGER_INCOMPLETE。",
    "// Model already covered → no incomplete event.": "// 模型已覆盖 → 无 incomplete event。",
    "// Sink model still usable for projection without new AI stage.": "// Sink model 无新 AI stage 仍可用于 projection。",
    "* Acceptance: static {@code entry:entry-ann-*} rows join PathRuns keyed as": "* Acceptance：static {@code entry:entry-ann-*} 行 join 键为",
    "* Acceptance: taint sinks project to contrast rows with entryRefs / taintPathId.": "* Acceptance：taint sink 投影为带 entryRefs / taintPathId 的 contrast 行。",
    "// Budget truncation is explicit and testable.": "// Budget truncation 显式且可测。",
    "// Minimal reuse of InterproceduralTaintAcceptanceTest shape.": "// 最小复用 InterproceduralTaintAcceptanceTest shape。",
    "* Acceptance: 401-only PathRuns keep static rows as STATIC_ONLY (never bypassed).": "* Acceptance：仅 401 PathRun 保持 static 行为 STATIC_ONLY（永非 bypassed）。",
    "* P0-18: entry × 0-n parameter compilation with empty-input rationale.": "* P0-18：entry × 0-n parameter 编译，含 empty-input rationale。",
    "* Bounded bytecode heuristic: Filter calling StpUtil becomes GuardSurface candidate.": "* 有界 bytecode 启发式：调用 StpUtil 的 Filter 成为 GuardSurface 候选。",
    "// Truncation visibility: when more type names than MAX, gap is recorded.": "// Truncation 可见性：type 名超过 MAX 时记录 gap。",
    "// Bytecode probe gate: sanitizers not probe-worthy.": "// Bytecode probe gate：sanitizer 非 probe-worthy。",
    "* P0-21 minimum acceptance fixtures without live Docker.": "* P0-21 最小 acceptance fixture，无 live Docker。",
    "* P0-21: PathTraceProjector acceptance.": "* P0-21：PathTraceProjector acceptance。",
    "* P0-21: PostureExperimentCompiler acceptance.": "* P0-21：PostureExperimentCompiler acceptance。",
    "* P0-21: RuntimePostureOrchestrator acceptance.": "* P0-21：RuntimePostureOrchestrator acceptance。",
    "* P0-21: TracePlanCompiler acceptance.": "* P0-21：TracePlanCompiler acceptance。",
    "* TracePlan vs PathTrace diff acceptance (PATH/TRIAGE injection + probe priority).": "* TracePlan vs PathTrace diff acceptance（PATH/TRIAGE 注入 + probe 优先级）。",
    "* P0-21: WorldPackPlanner acceptance.": "* P0-21：WorldPackPlanner acceptance。",
    "* P2 SCAFFOLDING: WarFrameworkAdapter + ServletFrameworkAdapter via SPI;": "* P2 SCAFFOLDING：经 SPI 的 WarFrameworkAdapter + ServletFrameworkAdapter；",
    "* neutral fact contract (WAR dynamic stays disabled; adapters emit HINT only).": "* 中性 fact contract（WAR dynamic 保持 disabled；adapter 仅 emit HINT）。",
    "* Acceptance: FORCED ENTRY_HIT enriches finding wire titles/pathRunRefs without elevating VERIFIED.": "* Acceptance：FORCED ENTRY_HIT  enrich finding wire title/pathRunRef，不提升 VERIFIED。",
    "* RememberMe cipher-key detection + Cookie-channel identity materials (acceptance only).": "* RememberMe cipher-key detection + Cookie-channel identity 材料（仅 acceptance）。",
    "* Fixture mirrors kvf {@code ShiroConfig#setCipherKey(Base64.decode(\"2AvVhdsgUs0FSA3SDFAdag==\"))}.": "* Fixture 镜像 kvf {@code ShiroConfig#setCipherKey(Base64.decode(\"2AvVhdsgUs0FSA3SDFAdag==\"))}。",
    "// Latin-1 blob containing the same class-constant strings present in kvf ShiroConfig.class": "// 含 kvf ShiroConfig.class 中相同 class-constant 字符串的 Latin-1 blob",
    "// Separate Utf8-like constants (NUL between) — mirrors real .class constant-pool layout.": "// 分离 Utf8-like constant（NUL 间隔）— 镜像真实 .class constant-pool layout。",
    "// Dictionary string alone in another class must NOT create a hit without setCipherKey.": "// 另一 class 中仅 dictionary 字符串无 setCipherKey 不得产生 hit。",
    "* Acceptance: rememberMe cipher hyp becomes a finding with STATIC_INFERRED + hypothesisId": "* Acceptance：rememberMe cipher hyp 成为带 STATIC_INFERRED + hypothesisId 的 finding",
    "// Generic deser-config hyp (not rememberMe detector) must not project via this path.": "// 通用 deser-config hyp（非 rememberMe detector）不得经此 path 投影。",
    "* Blade JwtProperties default sign-key lives in nested blade-starter-jwt; outer-only scans missed it": "* Blade JwtProperties default sign-key 在 nested blade-starter-jwt；仅 outer scan 会遗漏",
    "* Synthetic identity harvest/mint rules: no silent commercial Blade key fallback": "* Synthetic identity harvest/mint 规则：无 silent commercial Blade key fallback",
    "* P1-04 gate: serializable CFG, MethodSummary bottom-up, field/return/sanitizer hooks,": "* P1-04 gate：可序列化 CFG、MethodSummary bottom-up、field/return/sanitizer hook，",
    "* and CFG_VIEW preferring CfgBuilder.": "* 与优先 CfgBuilder 的 CFG_VIEW。",
    "// Chain longer than MAX rounds so the final round still changes → budget stop reason.": "// Chain 长于 MAX round 使末轮仍变化 → budget stop reason。",
    "// Declared AUDITED scope for P1-04: lightweight analysis.kernel (CfgBuilder /": "// P1-04 声明 AUDITED scope：轻量 analysis.kernel（CfgBuilder /",
    "// MethodSummary / FieldReturn) with stopReason/budget honesty — not full SSA/IFDS/points-to.": "// MethodSummary / FieldReturn）含 stopReason/budget 诚实 — 非完整 SSA/IFDS/points-to。",
    "// ADR-0002 remains PROPOSED; suggests ACCEPTED = continue light kernel + deepen self-developed.": "// ADR-0002 仍为 PROPOSED；建议 ACCEPTED = 继续轻 kernel + 深化自研。",
    "* P1-02: optional multi-header JWT + Flowable deploy AnalysisPack shapes": "* P1-02：可选 multi-header JWT + Flowable deploy AnalysisPack shape",
    "* P0-15: open-source selectable practical recall catalog + metrics gate.": "* P0-15：开源可选 practical recall catalog + metrics gate。",
    "* Local JARs are optional; without them scores are NOT_EVALUABLE (not a production recall claim).": "* Local JAR 可选；无则 score 为 NOT_EVALUABLE（非 production recall 声称）。",
    "* P1-04: synthetic static entry recall baseline — scores are development-only, not production recall.": "* P1-04：合成 static entry recall baseline — 分数仅 development，非 production recall。",
    "* P2 SCAFFOLDING: desktop-jlink.ps1 -DryRun success path with a fake JDK that provides jlink.": "* P2 SCAFFOLDING：desktop-jlink.ps1 -DryRun 成功路径，fake JDK 提供 jlink。",
    "* P0-21: path-debug domain contract round-trip and legacy compatibility.": "* P0-21：path-debug domain contract 往返与 legacy 兼容。",
    "* P2 SCAFFOLDING: GVISOR/KATA capability vocabulary + fail-closed enablement without attestation.": "* P2 SCAFFOLDING：GVISOR/KATA capability 词汇 + 无 attestation 的 fail-closed 启用。",
    "* Multi-round OpenAI/Anthropic tool-call → final via loopback HttpServer.": "* 多轮 OpenAI/Anthropic tool-call → 经 loopback HttpServer 到 final。",
    "* Optional {@code VEYRION_LIVE_PROVIDER=1} may dial real providers; default never does.": "* 可选 {@code VEYRION_LIVE_PROVIDER=1} 可 dial 真实 provider；默认永不。",
    "* P1-24: OpenAI/Anthropic outbound error classification, budget bounds, disabled kinds,": "* P1-24：OpenAI/Anthropic outbound 错误分类、budget bound、disabled kind，",
    "* and DNS/metadata rejection via loopback — without live external providers.": "* 与经 loopback 的 DNS/metadata 拒绝 — 无 live 外部 provider。",
    "* Declared AUDITED scope = loopback outbound reject/budget (not external-network interop).": "* 声明 AUDITED scope = loopback outbound reject/budget（非 external-network interop）。",
    "// Fixture transports must stay on loopback; this suite never dials public DNS/IP.": "// Fixture transport 须 stay loopback；本 suite 永不 dial 公网 DNS/IP。",
    "* P2 SCAFFOLDING: each hardening requirement has a fail-closed rejection assertion": "* P2 SCAFFOLDING：每条 hardening 要求有 fail-closed 拒绝断言",
    "// OpenSandboxException / IllegalArgumentException / SecurityException.": "// OpenSandboxException / IllegalArgumentException / SecurityException。",
    "* Digest-pinned TRUSTED_DOCKER runtime image, or blank when unavailable.": "* Digest-pinned TRUSTED_DOCKER runtime image，不可用时空白。",
    "* Order: {@code VEYRION_DOCKER_RUNTIME_IMAGE}, then local sandbox-pack tag digests.": "* 顺序：{@code VEYRION_DOCKER_RUNTIME_IMAGE}，再 local sandbox-pack tag digest。",
    "// Drain remainder so the child is not blocked on a full pipe.": "// Drain 剩余，避免子进程被满 pipe 阻塞。",
    "* Builds a minimal executable “Boot-shaped” JAR for TRUSTED_DOCKER live probes:": "* 为 TRUSTED_DOCKER live probe 构建最小可执行“Boot-shaped”JAR：",
    "* Main-Class hosts two HTTP routes; BOOT-INF carries Spring stubs for static entry discovery.": "* Main-Class 承载两 HTTP route；BOOT-INF 带 Spring stub 供 static entry discovery。",
    "// Without agent mock driver, still keep the process ready for HTTP probes.": "// 无 agent mock driver 仍保持进程就绪供 HTTP probe。",
    "// Runtime Main-Class must load from the JAR root classpath.": "// Runtime Main-Class 须从 JAR root classpath 加载。",
}


def apply_map(content: str) -> tuple[str, int]:
    n = 0
    for old, new in MAP.items():
        if old in content:
            content = content.replace(old, new)
            n += 1
    return content, n


def main() -> None:
    touched: set[str] = set()
    total = 0
    for path in ROOT.rglob("*.java"):
        rel = path.relative_to(ROOT).as_posix()
        if any(x in rel for x in ("/ai/", "/control/", "/worker/", "/verification/")):
            continue
        if path.suffix != ".java":
            continue
        text = path.read_text(encoding="utf-8")
        new_text, n = apply_map(text)
        if n and new_text != text:
            path.write_text(new_text, encoding="utf-8")
            touched.add(rel)
            total += n
    print(f"TOUCHED {len(touched)} files, {total} replacements")


if __name__ == "__main__":
    main()
