#!/usr/bin/env python3
"""Phase 2: analysis package comment translations (batch 1)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# (relative_path, old, new) — exact substring replacements
R = [
("src/main/java/com/aq/jvmsentinel/analysis/experiment/TracePlanCompiler.java",
 "/**\n * P0-21: compile static Entry/Guard/Effect facts into TracePlan observation targets.\n */",
 "/**\n * P0-21：将静态 Entry/Guard/Effect fact 编译为 TracePlan observation target。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/TracePlanCompiler.java",
 "     * Fill expectedGuards / effects / hops / parameter specs from static IR bindings.\n     * Never invents runtime FACT — provenance remains RULE_GENERATED / STATIC_SIGNATURE.",
 "     * 从静态 IR binding 填充 expectedGuards / effects / hops / parameter spec。\n     * 永不发明 runtime FACT — provenance 保持 RULE_GENERATED / STATIC_SIGNATURE。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/TracePlanCompiler.java",
 "                // Also accept owner-class match when annotation binding is incomplete.",
 "                // annotation binding 不完整时也接受 owner-class 匹配。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/TracePlanCompiler.java",
 "        // Entry-local preconditions (ROLE=…) are static guard expectations.",
 "        // Entry-local 前置条件（ROLE=…）为静态 guard expectation。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/TracePlanCompiler.java",
 "     * Compatible projection of legacy sink/taint path strings into expected hops/effects.\n     * Never invents FACT — provenance remains RULE_GENERATED / STATIC_SIGNATURE in TracePlan.",
 "     * legacy sink/taint path 字符串到 expected hop/effect 的兼容投影。\n     * 永不发明 FACT — TracePlan 中 provenance 保持 RULE_GENERATED / STATIC_SIGNATURE。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/TracePlanObservationDiff.java",
 "/**\n * Compare a compiled TracePlan (static expectations) against an observed PathTrace.\n * Used for PATH/TRIAGE prompt injection and probe prioritization — never elevates verification.\n */",
 "/**\n * 比较已编译 TracePlan（静态 expectation）与观测 PathTrace。\n * 用于 PATH/TRIAGE prompt 注入与 probe 优先级 — 永不提升 verification。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/TracePlanObservationDiff.java",
 "     * Pair each TracePlan with the best PathTrace for its entry (prefer matching",
 "     * 为每个 TracePlan 配对其 entry 的最佳 PathTrace（优先匹配"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/TracePlanObservationDiff.java",
 "     * a gap row so PATH/TRIAGE can prioritize unobserved expected effects.",
 "     * gap 行，以便 PATH/TRIAGE 优先未观测的 expected effect。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/TracePlanObservationDiff.java",
 "            // Prefer emitting gap rows first by sorting callers; here emit in order.",
 "            // 优先按 caller 排序 emit gap 行；此处按序 emit。"),
("src/main/java/com/aq/jvmsentinel/analysis/detector/AffectedDetectorRecompute.java",
 "/**\n * AUDIT_FLOW IR2: after PathTrace / PathRun observation, re-run the full detector suite\n * against current scan facts and merge hypotheses. Never elevates verification status;\n * preserves non-CANDIDATE lifecycles from prior observations.\n */",
 "/**\n * AUDIT_FLOW IR2：PathTrace / PathRun observation 后，对当前 scan fact 重跑完整 detector suite\n * 并合并 hypothesis。永不提升 verification status；\n * 保留先前 observation 的非 CANDIDATE lifecycle。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/ProbeParameterHeuristics.java",
 "/**\n * Bounded, charset-safe sample values for dynamic probe query/body binding.\n * Prefers honest exploration literals over empty input when a named parameter exists.\n * Values must survive {@code ProbeTarget.query} wire charset {@code [A-Za-z0-9_=&%./{}:-]}.\n */",
 "/**\n * dynamic probe query/body binding 的有界、charset-safe 样本值。\n * 存在命名 parameter 时优先诚实 exploration literal 而非空 input。\n * 值须 survive {@code ProbeTarget.query} wire charset {@code [A-Za-z0-9_=&%./{}:-]}。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/ProbeParameterHeuristics.java",
 "     * Explicit sample from simple {@code name=value} encodings; blank for structural",
 "     * 来自简单 {@code name=value} 编码的显式样本；结构性"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/ProbeParameterHeuristics.java",
 "            // Numeric literal: charset-safe and accepted by QLExpress / SpEL / Aviator / MVEL.",
 "            // 数字 literal：charset-safe，QLExpress / SpEL / Aviator / MVEL 可接受。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/ProbeParameterHeuristics.java",
 "     * Prefer a compiled query only when it binds at least one real entry parameter name;\n     * otherwise fall back to {@code fallback} (typically {@link #buildSyntheticQuery}).",
 "     * 仅当 compiled query 绑定至少一个真实 entry parameter 名时优先；\n     * 否则 fallback 到 {@code fallback}（通常 {@link #buildSyntheticQuery}）。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/ProbeParameterHeuristics.java",
 "            // Keep wire-safe: drop characters outside ProbeTarget query charset.",
 "            // 保持 wire-safe：丢弃 ProbeTarget query charset 外字符。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/EntryParameterExperimentCompiler.java",
 "/**\n * P0-18: compile entry × 0-n parameter space into server-owned experiment plans.\n * Empty query/body is a legal shape and must carry empty-input rationale.\n */",
 "/**\n * P0-18：将 entry × 0-n parameter space 编译为服务端 owned experiment plan。\n * 空 query/body 为合法 shape，须携带 empty-input rationale。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/EntryParameterExperimentCompiler.java",
 "     * Unify entry signatures, hypothesis families, DynamicProbe ExperimentPlans and AUTH PoC\n     * entry hints into server-owned compiled experiments (P0-18).",
 "     * 统一 entry signature、hypothesis family、DynamicProbe ExperimentPlan 与 AUTH PoC\n     * entry hint 为服务端 owned compiled experiment（P0-18）。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/PathTraceProjectionBridge.java",
 "/**\n * P0-21: project PathRun facts and agent event summaries into PathTrace.\n */",
 "/**\n * P0-21：将 PathRun fact 与 agent event summary 投影为 PathTrace。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/PathTraceProjectionBridge.java",
 "        // Keep chronological order. Drop CLASS_LOAD flood and duplicate GUARD noise so the\n        // TRACE budget retains Controller→Service→Util→Repository→Guard→Effect before failure.",
 "        // 保持时间序。丢弃 CLASS_LOAD flood 与重复 GUARD 噪声，使\n        // TRACE budget 在 failure 前保留 Controller→Service→Util→Repository→Guard→Effect。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/PathTraceProjectionBridge.java",
 "            // Keep only if sensor explicitly tagged a path-debug kind other than METHOD_HOP noise.",
 "            // 仅当 sensor 显式标记非 METHOD_HOP 噪声的 path-debug kind 时保留。"),
("src/main/java/com/aq/jvmsentinel/analysis/GuardSurfaceBytecodeProbe.java",
 "/**\n * Bounded bytecode heuristic for FORCED GuardSurface candidates.\n * Types implementing Filter / HandlerInterceptor (or Sa-Token equivalents) that call\n * Subject / SecurityContext / StpUtil / getToken become catalog candidates — still gated\n * by the server allowlist at runtime. Never elevates VERIFIED.\n */",
 "/**\n * FORCED GuardSurface 候选的有界 bytecode 启发式。\n * 实现 Filter / HandlerInterceptor（或 Sa-Token 等价物）且调用\n * Subject / SecurityContext / StpUtil / getToken 的类型成为 catalog 候选 — runtime 仍由服务端 allowlist gate。\n * 永不提升 VERIFIED。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/GuardSurfaceCatalog.java",
 "/**\n * Load-free harvest of auth/role/permission/license/feature guard type names from an artifact JAR.\n * Drives FORCED_REACHABILITY allowlists; never elevates VERIFIED and never targets sanitizers.\n */",
 "/**\n * 从 artifact JAR 无 load 采集 auth/role/permission/license/feature guard 类型名。\n * 驱动 FORCED_REACHABILITY allowlist；永不提升 VERIFIED，永不 targeting sanitizer。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/GuardSurfaceCatalog.java",
 "                // Skip synthetic/anonymous inners; keep named nested types that look like filters.",
 "                // 跳过 synthetic/anonymous inner；保留像 filter 的命名 nested type。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/GuardSurfaceCatalog.java",
 "                // Bounded bytecode heuristic for Filter/Interceptor calling auth APIs.",
 "                // Filter/Interceptor 调用 auth API 的有界 bytecode 启发式。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/GuardSurfaceCatalog.java",
 "            // Nested lib optional.",
 "            // Nested lib 可选。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/GuardSurfaceCatalog.java",
 "        // Shiro AccessControl decision filters (isAccessAllowed) — not outer chain binders.",
 "        // Shiro AccessControl decision filter（isAccessAllowed）— 非外层 chain binder。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/GuardSurfaceCatalog.java",
 "        // Container / infra bases — never force the outer chain binder.",
 "        // Container / infra base — 永不 force 外层 chain binder。"),
("src/main/java/com/aq/jvmsentinel/analysis/pack/FlowableDeployExperimentPack.java",
 "/**\n * Flowable / BPMN deploy-upload experiment shapes.\n * Multipart deploy probes stay non-destructive (no process start / no memory shell).\n */",
 "/**\n * Flowable / BPMN deploy-upload 实验 shape。\n * Multipart deploy probe 保持非破坏性（无 process start / 无 memory shell）。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/identity/AuthCodeQueryService.java",
 "/**\n * Bounded, load-free auth-surface query over a registered JAR/WAR.\n * Returns FACT-shaped observations for AI tools; never executes classes,\n * never opens network, and never elevates verification status.\n *\n * <p>Core harvest uses generic JWT/secret property patterns and auth filter/annotation\n * signals. Optional {@link com.aq.jvmsentinel.analysis.framework.FrameworkAdapter}\n * dictionaries contribute known-weak-key HINTs for in-artifact matching only — never\n * silent mint sources for a general platform.\n */",
 "/**\n * 对已注册 JAR/WAR 的有界、无 load auth-surface 查询。\n * 返回 AI tool 的 FACT 形 observation；永不执行 class、\n * 永不打开 network，永不提升 verification status。\n *\n * <p>核心 harvest 使用通用 JWT/secret property pattern 与 auth filter/annotation\n * signal。可选 {@link com.aq.jvmsentinel.analysis.framework.FrameworkAdapter}\n * dictionary 仅为 artifact 内匹配贡献 known-weak-key HINT — 永不\n * 作为通用 platform 的 silent mint source。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/hypothesis/SecurityHypothesisProjector.java",
 "/**\n * Compatible projection of legacy sink findings into SecurityHypothesis (P0-12).\n * Non-AUTH_GAP sinks → DATAFLOW; AUTH_GAP → GUARD_COVERAGE (no fake sink-none).\n * High-signal non-taint detector hypotheses may also project to findings (STATIC_INFERRED only).\n */",
 "/**\n * legacy sink finding 到 SecurityHypothesis 的兼容投影（P0-12）。\n * 非 AUTH_GAP sink → DATAFLOW；AUTH_GAP → GUARD_COVERAGE（无 fake sink-none）。\n * 高信号 non-taint detector hypothesis 亦可投影为 finding（仅 STATIC_INFERRED）。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/detector/HardcodedJwtSignKeyDetector.java",
 "/**\n * Surfaces well-known / hardcoded JWT signing keys embedded in artifact classes or nested\n * framework JARs (e.g. Blade {@code JwtProperties} default). CONFIG family only — never\n * elevates DYNAMIC_CONFIRMED / VERIFIED.\n */",
 "/**\n *  surfaced artifact class 或 nested framework JAR 中嵌入的 well-known / hardcoded JWT signing key\n *（如 Blade {@code JwtProperties} 默认）。仅 CONFIG family — 永不\n * 提升 DYNAMIC_CONFIRMED / VERIFIED。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/JvmSinkSignatures.java",
 "/**\n * High-signal JVM invocation catalog derived from the project Java audit checklist.\n *\n * <p>A match means only that a sensitive API call is present in bytecode. It does\n * not establish attacker control, runtime reachability, unsafe configuration, or\n * exploitability. Broad keywords such as {@code parse}, {@code read}, and\n * {@code execute} are deliberately never matched without an owner constraint.\n *\n * <p>Kinds are ordered primary-first. One call site may carry multiple security\n * effects (for example JDBC URL → SSRF + COMMAND + CLASS_LOADING). Consumers that\n * need a single label use {@link Match#category()}; full sets use {@link Match#kinds()}.\n */",
 "/**\n * 源自项目 Java audit checklist 的高信号 JVM invocation catalog。\n *\n * <p>匹配仅表示 bytecode 中存在敏感 API 调用。不\n * 建立 attacker control、runtime reachability、unsafe configuration 或\n * exploitability。{@code parse}、{@code read}、\n * {@code execute} 等宽泛 keyword 刻意在无 owner constraint 时不匹配。\n *\n * <p>Kind 按 primary-first 排序。单 call site 可携带多种 security\n * effect（如 JDBC URL → SSRF + COMMAND + CLASS_LOADING）。需要单 label 的消费者用 {@link Match#category()}；完整集合用 {@link Match#kinds()}。\n */"),
("src/main/java/com/aq/jvmsentinel/analysis/ArtifactMetadataReader.java",
 "* Bounded, metadata-only reader shared by CLI and Control Plane.",
 "* CLI 与 Control Plane 共享的有界、仅 metadata reader。"),
("src/main/java/com/aq/jvmsentinel/analysis/detector/Detector.java",
 "* Non-taint (and general) static detector contract (P1-05).",
 "* non-taint（及通用）静态 detector contract（P1-05）。"),
("src/main/java/com/aq/jvmsentinel/analysis/DynamicFeedbackApplier.java",
 "* Applies dynamic PathRun observations back as bounded evidence updates.",
 "* 将 dynamic PathRun observation 应用为有界 evidence 更新。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/PathTraceProjector.java",
 "* P0-21: project agent-like event summaries and PathRun facts into PathTrace without full trace stor",
 "* P0-21：将 agent-like event summary 与 PathRun fact 投影为 PathTrace，无需完整 trace stor"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/PostureExperimentCompiler.java",
 "* P0-21: compile entry × 0-n parameters × posture into server-owned experiment plans.",
 "* P0-21：将 entry × 0-n parameter × posture 编译为服务端 owned experiment plan。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/PathTraceGapAdvisor.java",
 "* P0-21: deterministic PATH/TRIAGE suggestions from PathTrace gaps.",
 "* P0-21：从 PathTrace gap 产生确定性 PATH/TRIAGE 建议。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/PathTraceObservationBridge.java",
 "* P0-21: project PathTrace events into RuntimeObservation kinds for hypothesis lifecycle.",
 "* P0-21：将 PathTrace event 投影为 hypothesis lifecycle 的 RuntimeObservation kind。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/PathTraceEvidenceGraphDelta.java",
 "* P0-21: convert PathTrace events into Evidence Graph delta nodes/edges.",
 "* P0-21：将 PathTrace event 转换为 Evidence Graph delta node/edge。"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/PathDebugWireHelper.java",
 "* P0-21: merge optional PathTrace / path-debug fields into PathRun API wire maps",
 "* P0-21：将可选 PathTrace / path-debug field 合并进 PathRun API wire map"),
("src/main/java/com/aq/jvmsentinel/analysis/experiment/DefaultExperimentPlanFactory.java",
 "* Server-side default ExperimentPlan candidates from SecurityHypothesis (P1-06).",
 "* 从 SecurityHypothesis 产生的服务端默认 ExperimentPlan 候选（P1-06）。"),
("src/main/java/com/aq/jvmsentinel/analysis/CoverageGapProjector.java",
 "* Projects STATIC_ONLY / uncovered taint steps into bounded CoverageGap hints for PATH_EXPLORATION.",
 "* 将 STATIC_ONLY / uncovered taint step 投影为有界 CoverageGap hint，供 PATH_EXPLORATION。"),
("src/main/java/com/aq/jvmsentinel/analysis/coverage/CoverageMatrixProjector.java",
 "* Read-only projection of scan facts into {@link CoverageMatrix}.",
 "* scan fact 到 {@link CoverageMatrix} 的只读投影。"),
("src/main/java/com/aq/jvmsentinel/analysis/contrast/ContrastLedger.java",
 "* Bounded CONTRAST_LEDGER for REPORT / PATH / TRIAGE prompts and server-side",
 "* REPORT / PATH / TRIAGE prompt 与服务端的有界 CONTRAST_LEDGER"),
("src/main/java/com/aq/jvmsentinel/analysis/contrast/StaticContrastProjector.java",
 "* Deterministic sink-perspective projection of existing {@link BytecodeFactIndex.TaintPath}",
 "* 现有 {@link BytecodeFactIndex.TaintPath} 的确定性 sink 视角投影"),
("src/main/java/com/aq/jvmsentinel/analysis/contrast/TaintPathCoverageJoiner.java",
 "* Deterministically joins static taint-path methods to bounded branch coverage observations.",
 "* 确定性 join 静态 taint-path method 与有界 branch coverage observation。"),
("src/main/java/com/aq/jvmsentinel/analysis/CandidateRanker.java",
 "* Deterministic sink ranking for PRE_ANALYSIS / dashboard. Scores are bounded heuristics,",
 "* PRE_ANALYSIS / dashboard 的确定性 sink 排序。分数为有界启发式，"),
("src/main/java/com/aq/jvmsentinel/analysis/ClassFileMetadataParser.java",
 "* Minimal, bounded classfile parser. It intentionally understands only the",
 "* 最小有界 classfile parser。刻意仅理解"),
("src/main/java/com/aq/jvmsentinel/analysis/BootPortCandidateHarvester.java",
 "* P0-17: harvest candidate application HTTP ports from Boot config lines / manifest text.",
 "* P0-17：从 Boot config 行 / manifest 文本 harvest 候选 application HTTP port。"),
("src/main/java/com/aq/jvmsentinel/analysis/BranchConstraintHarvester.java",
 "* Post-process parameter / flow summaries into {@link ParameterSpec} constraints without rebuilding",
 "* 后处理 parameter / flow summary 为 {@link ParameterSpec} constraint，无需重建"),
]

def main():
    n = 0
    for rel, old, new in R:
        path = ROOT / rel.replace("/", "\\")
        if not path.exists():
            print("MISSING", rel)
            continue
        text = path.read_text(encoding="utf-8")
        if old not in text:
            print("NO MATCH", rel[:60], old[:40])
            continue
        path.write_text(text.replace(old, new, 1), encoding="utf-8")
        n += 1
    print("Applied", n)

if __name__ == "__main__":
    main()
