package com.aq.jvmsentinel.dev;

import com.aq.jvmsentinel.control.ControlPlaneServer;
import com.aq.jvmsentinel.sandbox.LocalDockerTrustedSandboxClient;
import com.aq.jvmsentinel.worker.LocalArtifactWorkerLoop;

import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.SecureRandom;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.TimeUnit;

/**
 * Local-development launcher for the loopback Control Plane and Vite GUI.
 *
 * <p>When explicitly enabled, this launcher also starts the process-local trusted Docker
 * worker. The worker still consumes the authenticated contract and has no host JVM fallback.</p>
 */
public final class DevLauncherMain {
    private DevLauncherMain() { }

    public static void main(String[] args) throws Exception {
        Configuration config = Configuration.parse(args, Path.of("").toAbsolutePath());
        Files.createDirectories(config.artifactRoot());
        Path runtimeDir = config.artifactRoot().resolve(".veyrion");
        Files.createDirectories(runtimeDir);
        String token = loadOrCreateMutationToken(runtimeDir.resolve("mutation.token"));
        Path database = runtimeDir.resolve("control-plane.db");

        try (ControlPlaneServer server = new ControlPlaneServer(
                "127.0.0.1", config.backendPort(), config.artifactRoot(), token,
                database).start()) {
            LocalArtifactWorkerLoop worker = config.dockerArtifactWorker()
                    ? new LocalArtifactWorkerLoop(
                            server.baseUri().resolve("/internal/worker/v1/"),
                            server.workerToken(), new LocalDockerTrustedSandboxClient(),
                            server::requireLocalArtifact, requiredRuntimeImage()).start()
                    : null;
            // Do not bootstrap or force-select a default workspace; the GUI workspaces home owns that.
            syncFrontendEnv(config, server.baseUri(), token);
            Process frontend = startFrontend(config, server.baseUri(), token);
            Runtime.getRuntime().addShutdownHook(new Thread(
                    () -> {
                        stop(frontend);
                        if (worker != null) worker.close();
                    }, "veyrion-dev-shutdown"));

            System.out.println("Veyrion Control Plane: " + server.baseUri());
            System.out.println("Veyrion GUI: http://127.0.0.1:" + config.frontendPort());
            System.out.println("Authorized artifact directory: " + config.artifactRoot());
            System.out.println("Local GUI auth token synced to frontend/.env.local (loopback only)");
            System.out.println("No default workspace is created; open 工作区 to choose or create one.");
            System.out.println("Trusted internal JAR Docker worker: "
                    + (worker == null ? "disabled" : "enabled (TRUSTED_DOCKER, network none, network/DNS observation)"));
            System.out.println("Press Ctrl+C to stop both processes.");

            try {
                if (frontend.waitFor(2, TimeUnit.SECONDS)) {
                    throw new IllegalStateException(
                            "frontend exited during startup with code " + frontend.exitValue());
                }
                int exitCode = frontend.waitFor();
                if (exitCode != 0) throw new IllegalStateException("frontend exited with code " + exitCode);
            } finally {
                if (worker != null) worker.close();
            }
        }
    }

    static Process startFrontend(Configuration config, URI apiBaseUri, String token) throws IOException {
        ProcessBuilder builder = new ProcessBuilder(frontendCommand(config));
        builder.directory(config.frontendDirectory().toFile());
        builder.inheritIO();
        Map<String, String> environment = builder.environment();
        environment.put("VITE_DEMO_MODE", "false");
        environment.put("VITE_API_BASE_URL", apiBaseUri.toString());
        environment.put("VITE_API_TOKEN", token);
        environment.remove("VITE_PROJECT_ID");
        return builder.start();
    }

    static void syncFrontendEnv(Configuration config, URI apiBaseUri, String token) throws IOException {
        Path envLocal = config.frontendDirectory().resolve(".env.local");
        String content = """
                # Generated by DevLauncherMain for loopback development only.
                # Do not commit. Restart Vite after this file changes.
                # VITE_PROJECT_ID is intentionally omitted so the GUI does not force a workspace.
                VITE_DEMO_MODE=false
                VITE_API_BASE_URL=%s
                VITE_API_TOKEN=%s
                """.formatted(apiBaseUri, token);
        Files.writeString(envLocal, content, StandardCharsets.UTF_8);
    }

    static String loadOrCreateMutationToken(Path tokenFile) throws IOException {
        if (Files.isRegularFile(tokenFile)) {
            String existing = Files.readString(tokenFile, StandardCharsets.UTF_8).trim();
            if (existing.matches("[A-Za-z0-9_-]{16,128}")) {
                return existing;
            }
        }
        String token = randomToken();
        Files.writeString(tokenFile, token + System.lineSeparator(), StandardCharsets.UTF_8);
        return token;
    }

    static List<String> frontendCommand(Configuration config) {
        return List.of(config.npmExecutable(), "run", "dev", "--",
                "--host", "127.0.0.1",
                "--port", Integer.toString(config.frontendPort()),
                "--strictPort");
    }

    private static String randomToken() {
        byte[] value = new byte[32];
        new SecureRandom().nextBytes(value);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(value);
    }

    private static String requiredRuntimeImage() {
        String value = System.getenv("VEYRION_ARTIFACT_RUNTIME_IMAGE_URI");
        if (value == null || !value.matches("[a-z0-9.-]+(?::[0-9]{1,5})?"
                + "(?:/[A-Za-z0-9._-]+)+@sha256:[0-9a-f]{64}")) {
            throw new IllegalStateException("VEYRION_ARTIFACT_RUNTIME_IMAGE_URI is missing or invalid");
        }
        return value;
    }

    private static void stop(Process process) {
        if (process == null || !process.isAlive()) return;
        process.destroy();
        try {
            if (!process.waitFor(3, TimeUnit.SECONDS)) process.destroyForcibly();
        } catch (InterruptedException interrupted) {
            Thread.currentThread().interrupt();
            process.destroyForcibly();
        }
    }

    public record Configuration(Path workspace, Path artifactRoot, Path frontendDirectory,
                                int backendPort, int frontendPort, String npmExecutable,
                                boolean dockerArtifactWorker) {
        public Configuration {
            workspace = realDirectory(workspace, "workspace");
            artifactRoot = absoluteWithin(workspace, artifactRoot, "artifactRoot");
            frontendDirectory = realDirectory(frontendDirectory, "frontendDirectory");
            if (!frontendDirectory.startsWith(workspace)
                    || !Files.isRegularFile(frontendDirectory.resolve("package.json"))) {
                throw new IllegalArgumentException("frontendDirectory must be the workspace frontend");
            }
            if (backendPort < 1 || backendPort > 65535
                    || frontendPort < 1 || frontendPort > 65535
                    || backendPort == frontendPort) {
                throw new IllegalArgumentException("development ports are invalid");
            }
            Objects.requireNonNull(npmExecutable, "npmExecutable");
            if (npmExecutable.isBlank() || npmExecutable.length() > 1024
                    || npmExecutable.chars().anyMatch(c -> c < 0x20 || c == 0x7f)) {
                throw new IllegalArgumentException("npmExecutable is invalid");
            }
        }

        static Configuration parse(String[] args, Path defaultWorkspace) {
            Objects.requireNonNull(args, "args");
            Path workspace = defaultWorkspace;
            Path artifactRoot = null;
            int backendPort = 8080;
            int frontendPort = 5173;
            String npm = System.getProperty("os.name", "").toLowerCase().contains("win")
                    ? "npm.cmd" : "npm";
            Map<String, String> values = parseArguments(args);
            if (values.containsKey("workspace")) workspace = Path.of(values.get("workspace"));
            workspace = realDirectory(workspace, "workspace");
            artifactRoot = values.containsKey("artifacts")
                    ? Path.of(values.get("artifacts")) : workspace.resolve("samples");
            if (values.containsKey("backend-port")) {
                backendPort = port(values.get("backend-port"), "backend-port");
            }
            if (values.containsKey("frontend-port")) {
                frontendPort = port(values.get("frontend-port"), "frontend-port");
            }
            if (values.containsKey("npm")) npm = values.get("npm");
            boolean dockerArtifactWorker = values.containsKey("docker-artifact-worker")
                    && booleanValue(values.get("docker-artifact-worker"), "docker-artifact-worker");
            return new Configuration(workspace, artifactRoot, workspace.resolve("frontend"),
                    backendPort, frontendPort, npm, dockerArtifactWorker);
        }

        private static Map<String, String> parseArguments(String[] args) {
            Map<String, String> result = new LinkedHashMap<>();
            List<String> allowed = List.of(
                    "workspace", "artifacts", "backend-port", "frontend-port", "npm",
                    "docker-artifact-worker");
            for (int index = 0; index < args.length; index++) {
                String argument = args[index];
                if (!argument.startsWith("--") || !allowed.contains(argument.substring(2))
                        || index + 1 >= args.length) {
                    throw new IllegalArgumentException("unsupported or incomplete development option");
                }
                String key = argument.substring(2);
                String value = args[++index];
                if (value.isBlank() || result.putIfAbsent(key, value) != null) {
                    throw new IllegalArgumentException("duplicate or empty development option");
                }
            }
            return result;
        }

        private static int port(String value, String name) {
            try {
                int parsed = Integer.parseInt(value);
                if (parsed < 1 || parsed > 65535) throw new NumberFormatException();
                return parsed;
            } catch (NumberFormatException invalid) {
                throw new IllegalArgumentException(name + " must be a valid TCP port");
            }
        }

        private static boolean booleanValue(String value, String name) {
            if ("true".equalsIgnoreCase(value)) return true;
            if ("false".equalsIgnoreCase(value)) return false;
            throw new IllegalArgumentException(name + " must be true or false");
        }

        private static Path realDirectory(Path value, String name) {
            Objects.requireNonNull(value, name);
            try {
                if (!Files.isDirectory(value)) throw new IllegalArgumentException(name + " must be a directory");
                return value.toRealPath();
            } catch (IOException failure) {
                throw new IllegalArgumentException(name + " cannot be resolved", failure);
            }
        }

        private static Path absoluteWithin(Path workspace, Path value, String name) {
            Objects.requireNonNull(value, name);
            Path absolute = value.toAbsolutePath().normalize();
            if (!absolute.startsWith(workspace)) {
                throw new IllegalArgumentException(name + " must stay inside the workspace");
            }
            return absolute;
        }
    }
}
