package com.aq.jvmsentinel.instrumentation.mock;

import com.aq.jvmsentinel.instrumentation.AgentConfig;
import com.aq.jvmsentinel.instrumentation.AgentRuntime;
import com.aq.jvmsentinel.instrumentation.PathDebugDetail;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/** 记录 SQL 并返回空结果的最小 Connection（MOCK / RULE_GENERATED）。 */
final class VeyrionMockConnection implements Connection {
    private final String url;
    private boolean closed;
    private boolean autoCommit = true;

    VeyrionMockConnection(String url) {
        this.url = url;
        AgentRuntime.recordJdbc(getClass().getName(), "connect",
                Map.of("captureMode", "DEPENDENCY_MOCK",
                        "dependencyMode", "MOCK",
                        "provenance", "RULE_GENERATED",
                        "url", truncate(url)));
    }

    @Override
    public Statement createStatement() {
        return new VeyrionMockStatement(this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql) {
        return new VeyrionMockPreparedStatement(this, sql);
    }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        throw new SQLException("callable statements are not mocked");
    }

    @Override
    public String nativeSQL(String sql) {
        return sql;
    }

    @Override
    public void setAutoCommit(boolean autoCommit) {
        this.autoCommit = autoCommit;
    }

    @Override
    public boolean getAutoCommit() {
        return autoCommit;
    }

    @Override
    public void commit() {
    }

    @Override
    public void rollback() {
    }

    @Override
    public void close() {
        closed = true;
    }

    @Override
    public boolean isClosed() {
        return closed;
    }

    @Override
    public DatabaseMetaData getMetaData() {
        return VeyrionMockDatabaseMetaData.create(url, this);
    }

    @Override
    public void setReadOnly(boolean readOnly) {
    }

    @Override
    public boolean isReadOnly() {
        return true;
    }

    @Override
    public void setCatalog(String catalog) {
    }

    @Override
    public String getCatalog() {
        return "veyrion_mock";
    }

    @Override
    public void setTransactionIsolation(int level) {
    }

    @Override
    public int getTransactionIsolation() {
        return Connection.TRANSACTION_READ_COMMITTED;
    }

    @Override
    public SQLWarning getWarnings() {
        return null;
    }

    @Override
    public void clearWarnings() {
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) {
        return createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) {
        return prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency)
            throws SQLException {
        return prepareCall(sql);
    }

    @Override
    public Map<String, Class<?>> getTypeMap() {
        return Map.of();
    }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) {
    }

    @Override
    public void setHoldability(int holdability) {
    }

    @Override
    public int getHoldability() {
        return 0;
    }

    @Override
    public Savepoint setSavepoint() throws SQLException {
        throw new SQLException("savepoints are not mocked");
    }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException {
        throw new SQLException("savepoints are not mocked");
    }

    @Override
    public void rollback(Savepoint savepoint) {
    }

    @Override
    public void releaseSavepoint(Savepoint savepoint) {
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
        return createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
                                              int resultSetHoldability) {
        return prepareStatement(sql);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
                                         int resultSetHoldability) throws SQLException {
        return prepareCall(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) {
        return prepareStatement(sql);
    }

    @Override
    public Clob createClob() throws SQLException {
        throw new SQLException("unsupported");
    }

    @Override
    public Blob createBlob() throws SQLException {
        throw new SQLException("unsupported");
    }

    @Override
    public NClob createNClob() throws SQLException {
        throw new SQLException("unsupported");
    }

    @Override
    public SQLXML createSQLXML() throws SQLException {
        throw new SQLException("unsupported");
    }

    @Override
    public boolean isValid(int timeout) {
        return !closed;
    }

    @Override
    public void setClientInfo(String name, String value) {
    }

    @Override
    public void setClientInfo(Properties properties) throws SQLClientInfoException {
    }

    @Override
    public String getClientInfo(String name) {
        return null;
    }

    @Override
    public Properties getClientInfo() {
        return new Properties();
    }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
        throw new SQLException("unsupported");
    }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
        throw new SQLException("unsupported");
    }

    @Override
    public void setSchema(String schema) {
    }

    @Override
    public String getSchema() {
        return "public";
    }

    @Override
    public void abort(Executor executor) {
        closed = true;
    }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) {
    }

    @Override
    public int getNetworkTimeout() {
        return 0;
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("not a wrapper");
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) {
        return iface.isInstance(this);
    }

    boolean observeFailMode() {
        return "OBSERVE_FAIL".equalsIgnoreCase(
                System.getProperty(AgentConfig.WORLD_PACK_DEPENDENCY_MODE_PROPERTY, "MOCK_CONTINUE"));
    }

    /**
     * 为 PathRun/H3 记录语句 SQL。OBSERVE_FAIL 下调用方须在此
     * 返回后抛错，使请求保留失败前 PathTrace 证据并在依赖处退出。
     */
    void observeSql(String sql) {
        String text = sql == null ? "" : sql;
        String lower = text.toLowerCase(java.util.Locale.ROOT);
        String readWrite = lower.startsWith("select") || lower.startsWith("show") || lower.startsWith("explain")
                ? "READ"
                : lower.startsWith("insert") || lower.startsWith("update") || lower.startsWith("delete")
                || lower.startsWith("replace") ? "WRITE" : "UNKNOWN";
        boolean parameterized = text.contains("?");
        boolean malicious = lower.contains("'\"veyrion-sqli-meta");
        boolean observeFail = observeFailMode();
        Map<String, String> detail = new LinkedHashMap<>();
        detail.put("captureMode", "JDBC_STATEMENT");
        detail.put("dependencyMode", observeFail ? "OBSERVE_FAIL" : "MOCK");
        detail.put("provenance", observeFail ? "SERVER_FIXED_POLICY" : "RULE_GENERATED");
        detail.put("sql", truncate(text));
        detail.put("readWrite", readWrite);
        detail.put("parameterized", Boolean.toString(parameterized));
        detail.put("maliciousFragmentPresent", Boolean.toString(malicious));
        detail.put("parameterSummary", parameterized ? "jdbc-placeholders" : "inline");
        if (observeFail) {
            detail.putAll(PathDebugDetail.dependencyFailure("DEPENDENCY_UNAVAILABLE", truncate(text)));
        } else {
            detail.putAll(PathDebugDetail.dependencyCall(truncate(text)));
        }
        AgentRuntime.recordJdbc(getClass().getName(), "execute", detail);
    }

    private static String truncate(String value) {
        return value.length() <= 256 ? value : value.substring(0, 256);
    }
}
